### ISSUE TITLE
local `org-roam-db-location` not honored when running `org-roam-db-sync`

### ISSUE THREAD

**Issue by edgimar** [org-roam/org-roam#1917] opened 2021-10-22 03:30 UTC
### Description

My configuration defaults to the `org-roam-db-location` variable having a global value of  `~/.emacs.d/org-roam.db`, but I am using a `.dir-locals.el` file to set the variable locally to `/path/to/roam-files/org-roam.db`. 

When `org-roam-db-sync` is executed (with the local `org-roam-directory` definition active), *two* instances of `emacsql-sqlite.exe` are spawned, and `org-roam.db` files are created in *both* the global and the local locations.  The global db ends up containing info on all the nodes, while the local db only contains the node of the currently open file (which is within the `org-roam-directory`).

#### Steps to Reproduce

1. Delete any db files (while emacs is not running)
2. Load Emacs (for testing, `(org-roam-db-autosync-enable)` is *not* called in the init.el file).
3. Open a file in a folder containing the following `.dir-locals.el` file (and also containing a few other org-roam files):
```lisp
((nil . ((eval . (progn
                   (setq-local org-roam-directory (expand-file-name (locate-dominating-file default-directory ".dir-locals.el")))
                   (setq-local org-roam-db-location (expand-file-name (concat org-roam-directory "org-roam.db"))))))))
```
2. Run `org-roam-db-sync`   -- this should show the progress indicator as files are processed
3. Inspect the filesystem to confirm that two db files are generated (in the locations specified by the global and local `org-roam-db-location` values), and that one contains all the nodes, and the other only contains one node.

#### Expected Results

Only one db file is generated (in the location specified by the local `org-roam-db-location` value), and the db should contain information on all the roam nodes represented within the folder where `.dir-locals.el` resides.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)
 of 2021-08-27
- Framework: N/A
- Org: Org mode version 9.4 (9.4-27-g47bf60-elpaplus @ c:/Users/me/.emacs.d/elpa/org-plus-contrib-20201026/)
- Org-roam: 2.1.0

**Comment by josephmturner** [comment] 2021-10-31 08:01
Just noticed #1917. This might be a duplicate.

**Comment by soltanmm** [comment] 2022-01-05 23:48
I've seen this as well. I believe the problem is here: https://github.com/org-roam/org-roam/blob/679ef6ef001fd1a69b691108178721aa913e7f0f/org-roam-utils.el#L119

`run-mode-hooks` needs to fire to set dir-locals. These hooks are delayed by `delay-mode-hooks` until the next invocation of `run-mode-hooks`, which during a db-sync is never.

I can ameliorate the symptoms by tacking on a `(hack-local-variables)` call before this line: https://github.com/org-roam/org-roam/blob/679ef6ef001fd1a69b691108178721aa913e7f0f/org-roam-utils.el#L123

But as I only looked at this in the past hour or two I've got no idea if this is 'correct' with respect to the intentions of the authors. By the looks of things, `org-roam-with-file` isn't used anywhere besides node updating and migration, but I've never touched migration so *shrug*.

**Comment by jethrokuan** [comment] 2022-01-11 05:20
> run-mode-hooks needs to fire to set dir-locals.

I see. `delay-mode-hooks` was introduced to reduce time to sync for each file for those who have complex Org configurations. I'll add a call to `hack-local-variables` before the running the program body.

**Comment by jethrokuan** [comment] 2022-01-11 19:39
Merged the proposed patch into master, do check if the issue persists!

**Comment by leander-karp** [comment] 2022-01-13 18:13
On my machine, the issue is solved. Thank you for fixing this.

**Closed** 2022-01-16 05:31 UTC
