### ISSUE TITLE
[V2] 0a7d365 removes "Duplicate ID xxx, skipping..."

### ISSUE THREAD

**Issue by nobiot** [org-roam/org-roam#1496] opened 2021-04-30 16:36 UTC
### Description
Updated from 7416778 to 0a7d365 .
The new commit db-sync fails and terminates sync without more detail.
The previous commit used to skip the duplicate ID, completes the db-sync, and outputs a useful messge.

Could we get the lost behaviour back?

See the images below.

![image](https://user-images.githubusercontent.com/12507865/116724999-a66f9b80-a9e1-11eb-8dd8-1e7e8431741c.png)
Figure 1. From the new commit 0a7d365 

![image](https://user-images.githubusercontent.com/12507865/116725046-b9826b80-a9e1-11eb-8f08-028358df05da.png)
Figure 2. From the old commit 7416778 

#### Justification

My story goes like this (true story):

The new commit has introduced a new DB schema (with olp, etc.).
I have to rebuild the cache DB.  On Windows, forcing to clear the DB within Emacs does not work, so I delete the file in filesystem at the OS level.
I cannot not re-build the cache because of the duplication error.
I roll back the commit in order to go back to the backup DB file.
For some reason, I try `db-sync` one more time before going back to the backup DB file. I have got a useful message, manage to fix the duplicates, and move to the latest commit.

It's better to provide useful error messages to enable users to investigate and fix issues on their end.

#### Steps to Reproduce

1. Have a file that has a duplicate ID with another existing file in the cache
2. Run `org-roam-db-sync

#### Backtrace
No backtrace

#### Expected Results
Figure 2. From the old commit 7416778 

#### Actual Results
Figure 1. From the new commit 0a7d365 

### Environment
Hope the information above provides enough

**Comment by jethrokuan** [comment] 2021-05-02 08:52
I'll definitely add it back at some point, but I while I was working on Org-roam I realised that sometimes the error was something else, but because of the way the error is handled, it assumes that there is a duplication in ID, and prints a misleading error.

I suspect this is the case for the migration script: there are a couple of reports of duplicate IDs, but i'm thinking that the schema isn't yet updated to v2 on their end so the insertions just error out.

The programmatic errors are more useful for debugging right now, so I have removed them until a cleaner way to catch and report these errors are found.

**Comment by jmay** [comment] 2021-05-09 02:30
I think this is duplicate of #1480

**Comment by jmay** [comment] 2021-05-15 18:55
@nobiot Does 226669d resolve this?

**Comment by nobiot** [comment] 2021-05-16 15:38
@jmay, 
I have to admit it's a little hard to go back to the previous state and test it (it was part of DB scheme change).

It works great when you are saving a single buffer (current buffer). But it does not appear to do anything (no message output) when you run `org-roam-setup` or `org-roam-db-sync`. 

This issue I reported was for `org-roam-setup`. 

Is the commit relevant for it?

**Comment by jethrokuan** [comment] 2021-06-19 07:49
Addressed with `org-roam-db-query!`, introduced some time back.

**Closed by jethrokuan** 2021-06-19 07:49 UTC
Labels: v2
