### ISSUE TITLE
file+head should create folder which doesn't exist 

### ISSUE THREAD

**Issue by shadw3002** [org-roam/org-roam#1643] opened 2021-07-20 16:14 UTC
### Brief Abstract

for example: 

```lisp
(setq org-roam-capture-templates
	'(("n" "note" plain "%?" :if-new
           (file+head "%<%Y%m%d%H%M%S>/main.org" 
                      "#+TITLE: ${title}")
           :unnarrowed t
           :immediate-finish)))
```

### Long Description

when I invoke `org-roam-node-find`, it failed to create the directory, which leads to error.

**Comment by authsec** [comment] 2021-11-18 20:19
@jethrokuan I guess I added a possible duplicate of this issue here: https://github.com/org-roam/org-roam/issues/1971 I guess this may fix my issue as well.

**Closed** 2021-11-19 17:56 UTC
Labels: 1. enhancement
