### ISSUE TITLE
no backlinks even if backlinks are present

### ISSUE THREAD

**Issue by anildigital** [org-roam/org-roam#953] opened 2020-07-21 03:11 UTC
I am using org-roam for a while, but backlinks don't work 

```
../../org/talks/building_distributed_system_with_akka

* No backlinks!
```

```
Copy info below this line into issue:
- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287))
 of 2020-05-14
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/local/Cellar/emacs-plus/HEAD-747e0a2/share/emacs/27.0.91/lisp/org/)
- Org-roam: 1.2.0
```

**Comment by hsaito** [comment] 2020-07-21 05:39
Not sure if it's related, but I'm experiencing this exact problem, on Windows.

- Emacs: GnuEmacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
- Org: Org mode version 9.3.7 (9.3.7-14-gb2b587-elpa @ c:/users/*****/.emacs.d/site-lisp/org/lisp)
- Org-roam: 1.2.0 (but I've also tried ELPA version.)

Everything seems to be working except for backlinks. I've used sqlite3.exe (from binary release, also with self-compiled one with SQLITE_ENABLE_JSON1 option.) Seems to be no avail. I can generate the graph just fine, so it definitely aware of the links (and I can see al the fields are present when I opened the database file with Datagrip.

It looks like almost identical environment (except for the OS) on Linux seems to be getting the backlink correctly.

**Comment by hsaito** [comment] 2020-07-21 16:50
I found problem at least for Windows. (And probably also affected for original reporter more or less.

It turns out database stores file name starting "c:/Users/..." but org-roam is trying to retrieve data for "c:/users/..."

It is not returning appropriate value because of the case. Case sensitivity of the file system seems to be why this is happening...

**Comment by hsaito** [comment] 2020-07-21 17:17
Adding some more info, it looks like buffer-file-name is returning lower case variant (it seems like to be only affecting the beginning of the file name, e.g. Users vs users in my case) and the rest seems to use upper case variant of Users. (So the where this is affected on Mac may vary...)

**Comment by hsaito** [comment] 2020-07-21 18:19
Sorry for the multiple comments one after another. But it seems to be that invariance came from HOME variable. Once I changed home variable to have correct case, the issue resolved and this started working.

**Comment by anildigital** [comment] 2020-07-22 04:04
@hsaito How did you do that? Which variable specifically?

**Comment by hsaito** [comment] 2020-07-22 04:19
Mac being UNIX based I'm pretty sure your home variable's already set, but if you do echo $HOME, you should be able to see how it's set. (On Windows this is under by default, so I had to set one to use some of the tools including Emacs and I have neglected to be mindful of the case, this this problem happened.)

But you may want to see if the your HOME variable and M-x eval-expression buffer-file-name have similar case. If different, you may have to adjust your HOME variable... (Not sure exactly how, on Mac myself...)

**Comment by myshevchuk** [comment] 2020-07-25 17:59
@hsaito @anildigital These are clearly two separate issues and I don't think they have anything to do with case sensitivity of the file system. MacOS file systems are by default case insensitive, while Linux file systems are case sensitive, and org-roam/sqlite tandem works quite well on these platforms. Moreover, there is no need on MacOS to adjust the $HOME variable, 100%. 

@hsaito It's good that you've figured your problem, which definitely results from the mixed case. Emacs treats file names in a case-sensitive manner, and the value of your $HOME envvar somehow got through, while as you said Emacs functions return lower case file names. This may be worth investigating, but we don't use Windows (un)fortunately, so not sure when. For future, just remember that Emacs in general, not only org-roam, treats filenames as on UNIX - in a case sensitive manner, although Windows usually treats them case insensitive (despite the fact that NTFS filesystem itself is case sensitive).

@anildigital  What is this exactly:

> ../../org/talks/building_distributed_system_with_akka

Is it a text from org-roam buffer, or a link in your org-roam note?

**Comment by anildigital** [comment] 2020-07-25 18:01
It’s shown in org-roam-backlinks mode buffer. This is wrong. I need see a backlink listed there.  It’s not working for me.

**Comment by myshevchuk** [comment] 2020-07-25 21:16
I'm very sorry for you, but the information you provided is not enough to reproduce this issue.

Did it work for you and then something went wrong or was it wrong from the very beginning when you started to use `org-roam`?

**Comment by myshevchuk** [comment] 2020-07-26 18:37
Possibly a duplicate of #869

@anildigital look at the solution in #869, maybe it will help you.

**Comment by anildigital** [comment] 2020-07-27 05:51
@myshevchuk I am using a symlink to Dropbox folder

```bash
anil@mbp ~> ls -ltra org
lrwxr-xr-x  1 anil  staff  23 Jun 10 09:57 org@ -> /Users/anil/Dropbox/org
```

**Comment by myshevchuk** [comment] 2020-07-27 08:18
@anildigital do you have `directory-abbrev-alist` variable set?

Try this
1. Put this is your config file (setq org-roam-directory (file-truename "~/org"))
2. Restart Emacs

See if backlinks are working, if not then try

3. `M-x org-roam-db-clear`
4. `M-x org-roam-build-cache`
5. Restart Emacs

**Comment by anildigital** [comment] 2020-07-27 09:20
@myshevchuk 
```
(print directory-abbrev-alist)
```
it prints as `nil`

`org-roam-db-clear` and then `org-roam-build-cache` didn't help

**Comment by myshevchuk** [comment] 2020-07-27 09:35
@anildigital Did you do `(setq org-roam-directory (file-truename "~/org"))`?

**Comment by anildigital** [comment] 2020-07-27 09:36
Yes. This didn't help.

**Comment by myshevchuk** [comment] 2020-07-27 09:38
Well, without your org-roam config, it's very hard to tell anything else.

**Comment by myshevchuk** [comment] 2020-07-27 09:45
@anildigital Also, from your `org-roam-diagnostics` report, you are using the built-in `org`. Is it really so?

**Comment by anildigital** [comment] 2020-07-27 09:48
@myshevchuk 

My org-roam config
```
(use-package org-roam
      :ensure t
      :init
      (setq org-link-file-path-type 'adaptive)
      (setq org-roam-directory (file-truename "~/org"))      
      :hook
      (after-init . org-roam-mode)
      :custom
      ;; (org-roam-directory "/Users/anil/Dropbox/org")
      (org-roam-index-file "/Users/anil/Dropbox/org/index.org")
    
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n j" . org-roam-jump-to-index)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-graph-show)
               )
              :map org-mode-map
              (("C-c n i" . org-roam-insert))
              (("C-c n I" . org-roam-insert-immediate))))
```

org-roam-diagnostics

```
- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287))
 of 2020-05-14
- Framework: I don't know
- Org: Org mode version 9.3 (release_9.3 @ /usr/local/Cellar/emacs-plus/HEAD-747e0a2/share/emacs/27.0.91/lisp/org/)
- Org-roam: 1.2.0
```

**Comment by myshevchuk** [comment] 2020-07-27 10:53
@anildigital
1. So, your real `org` directory is `/Users/anil/Dropbox/org`, right?
2. Do you have any other org-mode related config?
3. Are you using Doom or Spacemacs maybe or just out-of-box Emacs?

**Comment by anildigital** [comment] 2020-08-02 14:54
@myshevchuk That's correct. I do have org-mode related config. Here it is https://gist.github.com/4230fba5f8849e4094f1c30544d22169

**Comment by myshevchuk** [comment] 2020-08-02 19:14
@anildigital It seems that you should not put (setq org-roam-directory ...) in `:init` section - that's too early. You should use either `:customize` org `:config` section `use-package:
``` elisp
(use-package org-roam
...
:custom
(org-roam-directory "/Users/anil/Dropbox/org")
...)
```

or

``` elisp
(use-package org-roam
...
:config
(setq org-roam-directory "/Users/anil/Dropbox/org")
...)
```

I believe, the same is true for `org-link-file-path-type`. The `:init` section of `use-package` is for special use, normally config goes into `:config`.

Then, you do not need to use `file-truename` on a full path, e.g "/Users/anil/Dropbox/org" (although it does not harm).
I meant using it with symlinks`(file-truename "~/org")`. Strictly said, it's also not necessary, because `org-roam` normally handles symlinks. It's just in case.

So far so good, I'm able to load `org-roam` with vanilla Emacs and the config you provided, and the backlinks are working. You just need to move `(setq org-roam-directory ...` into `:custom` or `:config` section.

If it still does not work for you, then there must be something else in your `.emacs` or `init.el` that breaks `org`/`org-roam` loading. The fact that `org-roam-diagnostics` reports the built-in `org` version indirectly indicates that. In the vanilla setup I tried, as soon as I have MELPA in my package archives, `org` is installed from there. And you I guess have MELPA initialized because you somehow installed `org-roam`.

Anyway, this does not seem to be an `org-roam` problem.

**Comment by anildigital** [comment] 2020-08-03 04:22
@myshevchuk Here is the latest config https://gist.github.com/7ffd741febc0f32bb10ae1124c32ad78 and it's still not working. I did clear and rebuild the org-roam db.

```
Copy info below this line into issue:
- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G73))
 of 2020-07-29
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/local/Cellar/emacs-plus@27/27.0.91/share/emacs/27.0.91/lisp/org/)
- Org-roam: 1.2.1
```

```
org-roam-directory is a variable defined in ‘org-roam.el’.
Its value is "/Users/anil/Dropbox/org"
Original value was 
"/Users/anil/org-roam/"

  You can customize this variable.

Documentation:
Default path to Org-roam files.
All Org files, at any level of nesting, are considered part of the Org-roam.
```

**Comment by anildigital** [comment] 2020-08-03 06:00
So after a lot of tries, I settled on following which has absolute path

```elisp
  (setq org-roam-directory (file-truename "~/Dropbox/org"))
  (setq org-roam-index-file "~/Dropbox/org/index.org")
```

Basically symlinks don't work as I use symlinks in org-mode config as well. Maybe org-roam relies on those symlinks from org as well and that's the reason it didn'twork

**Comment by myshevchuk** [comment] 2020-08-03 09:35
@anildigital, no. I've got everything working with exactly your setup: 
1. I used the configuration gist you provided
2. `~/Dropbox/org` is symlinked to `~/org`
3. I even actually installed Dropbox for that. 

There is nothing wrong on the org-roam's side:

<img width="593" alt="Screenshot 2020-08-03 at 11 26 47" src="https://user-images.githubusercontent.com/24212814/89167845-392af900-d57c-11ea-87c4-488a26c66cac.png">

I see only two possibilities:
1. Something's wrong elsewhere else in your `.emacs` or `init.el`, for example there are other `org`/`org-roam` or symbolic links-related settings that you did not share.
2. Potentially, if you use Dropbox Smart Sync, it can cause problems. I don't know how exactly it is implemented and cannot test it because I don't have a premium account.

You can also try to close Emacs, remove `org-roam.db` manually, and start Emacs once again.

**Comment by lwkz** [comment] 2020-09-08 07:15
I can replicate both behaviours. 

I have two Macs with the exact same Emacs configuration (symlink `.init.el` from Dropbox), and my notes are stored in Dropbox and symlinked into my home directories. I was randomly getting 'No Backlinks!' on one of the computers but recently it started to happen on both computers. I kept rebuilding `org-roam.db` and restarting Emacs all only with limited success. Removed symlinks and haven't had this issue since. I suspect there is something wrong with my Emacs config somewhere but wasn't able to pinpoint it as it seemed to be a random occurrence.

**Comment by myshevchuk** [comment] 2020-09-08 07:35
@lwkz Unless you use `directory-abbrev-alist` to set symlinks (see #869 and #1063), that's almost surely some loading issues on the side of your configuration file. Try disabling most or all of your config and reenable it piece by piece to find the source of the problem. 

Sometimes a "random" behaviour starts happening after an update. In such case, it is a good idea to purge and reinstall any external packages to get rid of stale `*.elc` files. Org mode is well known for such issues. The problem is there are usually two version of Org mode installed on a user's computer, the one shipped with Emacs and the other one installed by user via a package manager. Only one version should be loaded at a time. If both are, problems of different sorts appear that may impact both run-time and compilation.

**Comment by jethrokuan** [comment] 2020-09-14 04:41
Please check if #1099 has fixed this,

**Comment by anildigital** [comment] 2020-09-14 08:52
I just checked. It seems to work now.

Here is my current setup
```
- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G73))
 of 2020-08-12
- Framework: N/A
- Org: Org mode version 9.3 (release_9.3 @ /usr/local/Cellar/emacs-plus@27/27.1/share/emacs/27.1/lisp/org/)
- Org-roam: 1.2.1
```

**Closed** 2020-09-14 09:08 UTC

**Comment by shelper** [comment] 2020-12-10 11:57
Can you explain how you made this work ?
i have the same issue on windows. ....

> I just checked. It seems to work now.
> 
> Here is my current setup
> 
> ```
> - Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G73))
>  of 2020-08-12
> - Framework: N/A
> - Org: Org mode version 9.3 (release_9.3 @ /usr/local/Cellar/emacs-plus@27/27.1/share/emacs/27.1/lisp/org/)
> - Org-roam: 1.2.1
> ```

**Comment by saurabhkukade** [comment] 2021-08-14 20:26
I faced the similar issue and fixed this by installing and upgrading the following prerequisites.

`;; Package-Requires: ((emacs "26.1") (dash "2.13") (f "0.17.2") (org "9.4") (emacsql "3.0.0") (emacsql-sqlite "1.0.0") (magit-section "2.90.1"))`

reference: [org-roam.el](https://github.com/org-roam/org-roam/blob/master/org-roam.el)
