### ISSUE TITLE
org-roam-capture fails: (void-function org-roam-node-read)

### ISSUE THREAD

**Issue by fapdash** [org-roam/org-roam#1667] opened 2021-07-24 10:08 UTC
#### Steps to Reproduce

Execute `M-x org-roam-capture`.

#### Backtrace
```
Debugger entered--Lisp error: (void-function org-roam-node-read)
  org-roam-node-read()
  org-roam-capture(nil)
  funcall-interactively(org-roam-capture nil)
  call-interactively(org-roam-capture record nil)
  command-execute(org-roam-capture record)
  counsel-M-x-action("org-roam-capture")
  ivy-call()
  ivy-read("M-x " ("org-roam-capture" "package-list-packages" "orb-note-actions" "version" "org-ref-ivy-cite-completion" "org-roam-migrate-wizard" "org-roam-setup" "org-clock-in" "org-clock-out" "org-refile-to-datetree" "org-capture" "org-agenda" "fap/my-open-calendar" "ag-project" "my/org-insert-link" "crux-delete-file-and-buffer" "org-columns" "anzu-query-replace" "vterm" "org-cliplink" "smerge-keep-current" "org-journal-new-entry" "package-delete" "robe-start" "org-super-agenda-mode" "package-install" "projectile-replace" "git-timemachine-toggle" "org-refile" "magit-blame" "projectile-ag" "org-sparse-tree" "org-toggle-checkbox" "iedit-mode" "org-insert-link" "multi-vterm-dedicated-toggle" "inf-ruby-console-auto" "customize" "dumb-jump-go" "org-deadline" "org-gcal-fetch" "org-store-link" "git-timemachine" "deadgrep" "rg-project" "eval-buffer" "anzu-replace-at-cursor-thing" "robe-jump" "org-reload" "fzf-git-files" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

```

```
org-roam-capture-templates is a variable defined in ‘org-roam-capture.el’.
Its value is
(("d" "default" plain "%?" :if-new
  (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}
")
  :unnarrowed t))
```

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-06-04
- Framework: N/A
- Org: Org mode version 9.4.6 (9.4.6-gab9f2a @ /home/fap/.emacs.d/elpa/org-9.4.6/)
- Org-roam: 2.0.0

**Comment by jethrokuan** [comment] 2021-07-24 10:25
Please remove any deferred loading, or `(require 'org-roam)` once before running the functions. This is a duplicate of #1590 .

**Closed** 2021-07-24 10:25 UTC

**Comment by craigchen** [comment] 2021-08-12 12:37
I encountered similar problem. I deleted magit under ~/.emacs.d/elpa and reinstalled org-roam. Then my problem was solved.
