### ISSUE TITLE
org-roam-node-find or org-roam-node-insert  not showing nodes

### ISSUE THREAD

**Issue by jaavedd9** [org-roam/org-roam#2165] opened 2022-04-19 13:32 UTC
After running `org-roam-db-sync` on emacs (29.0.50), I don't see nodes anymore with "org-roam-node-find" command, trying to find or insert nodes just shows the history, when I select history node it prompts me to select the roam template - as if I am creating a new node. I installed emacs 28.1, re-installed all packages, that did not solve the problem. Using org-roam version 2.2.1.

The output of `org-roam-db-diagnose-node`

```
#s(org-roam-node nil nil nil nil nil "9e8a966b-4220-4b54-b29d-ba5317c8ac7e" nil 129 nil nil nil nil nil nil nil nil nil nil) [2 times]

```
I tried deleting the 'org-roam.db' database and ran the `org-roam-db-sync` command, but this did not work either.

**Comment by nobiot** [comment] 2022-04-23 15:08
Not sure if you have already managed to solve the issue.

Can you add a new node? -- if so, the DB is working. It is possible that somehow your `org-roam-directory` setting has changed and now points to an empty directory (?).

I use the Emacs version 28.1 on my Ubuntu Linux and has not issue with Org-roam.

With the information you provided, there is not much we can do. I have also used 29.0.50 that I compiled myself and has no issue with Org-roam. I switched from 29.0.50 to 28.1 as the latter has been released as a stable version -- on either versions, I cannot reproduce the issue you report.

**Comment by jaavedd9** [comment] 2022-04-24 07:55
my `org-roam-directory` is pointing to the right directory (that contains org roam files) and `org-roam-db-location` contains the `org-roam.db` file , I deleted this file and after the `org-roam-db-sync` function it is creating the deleted db file again. But it not showing either existing nodes or new nodes created; after creating a test node, when I try  to find newly created node, I see this:
![image](https://user-images.githubusercontent.com/38977172/164966114-2863bd99-3d03-45e0-8fe2-548f4928f4da.png) and selecting the node shown in history is creating new node again.

My org-roam configurations
```
(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory  (file-truename(concat dropbox-path  "emacs/org_files/org_roam/files/")))
  (org-roam-dailies-capture-templates
   '(("d" "default" plain "%?"
      :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                         "#+title: ${title}\n")
      :unnarrowed t)
     ("m" "meeting" entry
      #'org-roam-capture--get-point
      "* %<%I:%M %p> - %^{Meeting Title}  :meetings:\n\n%?\n\n"
      :file-name "Journal/%<%Y-%m-%d>"
      :olp ("Log")
      :head "#+title: %<%Y-%m-%d %a>\n\n[[roam:%<%Y-%B>]]\n\n")))
  :bind
  (("C-c n l" . org-roam-buffer-toggle)
   ("C-c n f" . org-roam-node-find)
   ("C-c n g" . org-roam-graph)
   ("C-c n i" . org-roam-node-insert)
   ("C-c n c" . org-roam-capture)
   ;; Dailies
   ("C-c n j" . org-roam-dailies-capture-today))
  :config
  (org-roam-setup)
  (org-roam-db-autosync-mode)
  (setq org-roam-completion-everywhere t)
  (setq org-roam-db-location
      (concat org-roam-directory "/.database/org-roam.db"))
  )
```
@nobiot

**Comment by nobiot** [comment] 2022-04-24 08:13
I suggest the following: 

1. Remove `org-roam-setup` -- it only does what the following line does, to activate `org-roam-db-autosync-mode` and is obsolete (refer to the docstring)  -- this is not an issue in itself of course
3. Place `  (setq org-roam-db-location` before `org-roam-setup` and `org-roam-db-autosync-mode`

When you activate `org-roam-db-autosync-mode`, it will also call `org-roam-db-sync` inside it. I think what's happening is this: Because your config calls `org-roam-db-sync` before you set custom DB location, you will create the DB file in the default file location. You then override it with your custom location.

**Comment by reteo** [comment] 2022-04-24 20:06
I'm getting the same behavior.  I just finished reinstalling my configuration (it's a self-contained system that uses "straight" to install all its packages). Before the reinstall, my nodes were showing up when using org-roam-node-find and org-roam-capture.  However, following a complete nuke and pave, which included wiping out the sqlite database, it no longer works; I am getting the sense that the newly-made database is not regenerating the index.  In fact, despite the fact that I have a lot of index entries, org-roam-db-sync takes absolutely no time to regenerate the index, which suggests that it is not finding the correct information to index it.

Here is my config file specific to org-roam:

``` 
;;; org-roam-config.el --- Org-Roam Configuration -*- lexical-binding: t -*-

;;; Commentary:

;; A plain-text personal knowledge management system.

;;; Code:

;; Just testing to see if this will allow org-roam-find-nodes to work.

(straight-use-package 'org-roam)

;; This is the directory where nodes are stored.
(setq org-roam-directory (file-truename "/home/reteo/SyncThing/Organizer/Knowledge"))

;; This is the acknowledgement that I know I'm using the second version.
(setq org-roam-v2-ack t)

;; I want some keybindings to avoid needing the command line.
(global-set-key (kbd "<f12> o n f") 'org-roam-node-find)
(global-set-key (kbd "<f12> o n i") 'org-roam-capture)

;; This function will use ripgrep to search through the knowledgebase
(defun bms/org-roam-rg-search ()
  "Search org-roam directory using consult-ripgrep. With live-preview."
  (interactive)
  (let ((consult-ripgrep-command "rg --null --ignore-case --type org --line-buffered --color=always --max-columns=500 --no-heading --line-number . -e ARG OPTS"))
    (consult-ripgrep org-roam-directory)))

;; And let's bind this to a key.
(global-set-key (kbd "<f12> o n s") 'bms/org-roam-rg-search)

;; Now that it's set up, let's make sure the database is up-to-date.
(org-roam-db-autosync-mode)

(provide 'org-roam-config)

;;; org-roam-config.el ends here
```

**Comment by nobiot** [comment] 2022-04-25 06:08
@reteo 
- Can you create new notes using `org-roam-node-find` or capture? 
- Can you find the new files in the same directory?

If the answer to both the questions is "Yes", I suggest you look at your existing files and see if you notice anything different -- e.g. check if there is anything wrong with their ID. 

I just deleted my db file and built the db again on 28.1, and cannot reproduce the problem. There is not much we can do.

**Comment by reteo** [comment] 2022-04-25 11:50
First of all, I can understand being tied up due to non-replication of issue, so no worries there.  I can perform tests and respond as needed.

Now, when I create nodes, they are saved in the right place and given IDs.  Additionally, I've looked through the files for the previous nodes, and the IDs retain the same formatting.

One thing of note: while the new node file was saved in the correct location with a correct-looking ID, subsequent lookups remain empty; the new node is not appearing.

**Comment by jaavedd9** [comment] 2022-04-25 12:29
> I suggest the following:
> 
> 1. Remove `org-roam-setup` -- it only does what the following line does, to activate `org-roam-db-autosync-mode` and is obsolete (refer to the docstring)  -- this is not an issue in itself but might be confusing later
> 2. Place `  (setq org-roam-db-location` before `org-roam-setup` and `org-roam-db-autosync-mode`
> 
> When you activate `org-roam-db-autosync-mode`, it will also call `org-roam-db-sync` inside it. I think what's happening is this: Because your config calls `org-roam-db-sync` before you set custom DB location, you will create the DB file in the default file location. You then override it with your custom location.

@nobiot  tried this, but did not help.

**Comment by nobiot** [comment] 2022-04-25 15:36
@jaavedd9 @jaavedd9 

I have tried to reproduce with `emacs -q` with no other configuration than the following and Org-roam. 
I cannot reproduce the issue. `org-roam-diagnostics` produces the following:

```
- Emacs: GNU Emacs 28.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
 of 2022-04-15
- Framework: none
- Org: Org mode version 9.5.2 (release_9.5.2-25-gaf6f12 @ /usr/local/share/emacs/28.1.50/lisp/org/)
- Org-roam: 2.2.1- sqlite-connector: sqlite
```

The only thing I can suggest is to try vanilla (`emacs -q`) after you backed up your configuration. And then incrementally test your piece of configuration for Org-roam to identify what's causing your issue.

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(global-set-key (kbd "C-c n /") #'org-roam-node-find)
```

![Screenshot from 2022-04-25 17-30-48](https://user-images.githubusercontent.com/12507865/165122438-80dcd74f-b54a-4345-9ce1-429e047e5e9e.png)

**Comment by nobiot** [comment] 2022-04-25 15:42
@molekular 
Since your Linux desktop works, I suspect your issue is different. Termux + Android is known to have issues with Orgg-roam; see this [issue](https://github.com/org-roam/org-roam/issues/1605). 

You didn't say this, but if you happen to have the ""middleware out of memory" error on Termux +Android, [this](https://github.com/skeeto/emacsql/issues/78) might provide a solution (see the PR linked to this issue on emacsql repo).

**Comment by molekular** [comment] 2022-04-25 16:14
@nobiot 
Thank you for this hint. I do not have the "middleware out of memory" error, still tried both workarounds suggested there, to no avail. I will silently follow this issue here, it seems closest to my issue. Thanks again!

**Comment by nobiot** [comment] 2022-04-25 16:27
@molekular just in case (but i think you are aware) the change of code in the second link requires the `emacql` executable (binary) to be recompiled — you’d probably need to delete the current binary and then get Emacs to recompile it…

**Comment by reteo** [comment] 2022-04-25 18:38
I just tried without any packages but emacSQL, org-mode, and org-roam.  Still nothing.

Also, here are the details on my (testing) installation; it seems to be slightly newer than yours, so maybe there was a slight change in one of the other modules?
```
Copy info below this line into issue:
- Emacs: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)
 of 2022-04-04
- Framework: 
- Org: Org mode version 9.5.3 (9.5.3-g407104 @ /home/reteo/.emacs.test.d/straight/build/org/)
- Org-roam: v2.2.2-2-gb63ff2a
- sqlite-connector: sqlite
```

 In addition to the above information, my EmacSQL is currently version 3.0.0, in case that helps.

**Comment by nobiot** [comment] 2022-04-25 19:46
I see.... The only possibility I can think of now is that the cause is outside Emacs; and that should (must) be the `emacsql-sqlite` executable file.

It's probably either of the two:

1. You now don't have a C-compiler and Emacs didn't compile `emacsql-sqlite` executable (despite Emacs showing message to this effect in the echo
2. You now don't have permission to execute the `emacsql-sqlite` file -- e.g. you recovered the Emacs config folder from a backup done by another user name (this was one of the issues I helped with in the past somewhere here or the Discourse forum)

Please try confirming this in the filesystem or Emacs Dired. See the permission and location of the executable file in my screen shot. 

If neither of two above the cause, I have run out of ideas. 

![Screenshot from 2022-04-25 21-35-17](https://user-images.githubusercontent.com/12507865/165161659-6fa40fdb-126b-44ac-878e-ea4a56ccb20f.png)

**Comment by reteo** [comment] 2022-04-25 20:28
Unfortunately, neither is the case (everything is from the same uid, and emacsql is compiled.

And you are not able to replicate using 2.2.2 of org-roam?  Looking at your info list, it shows 2.2.1, the previous version.

**Comment by jaavedd9** [comment] 2022-04-25 20:45
![image](https://user-images.githubusercontent.com/38977172/165171705-be05a774-76ee-4716-804f-5e16377e33a0.png)
@nobiot  `emacsql-sqlite`is compiled and has right permissions

**Comment by nobiot** [comment] 2022-04-25 20:55
When you tested with the minimal set up, you used configuration under `emacs.test.d` directory. Is this correct?
Then I don't see it contain the executable.

![2022-04-25T224616](https://user-images.githubusercontent.com/12507865/165172445-dbbf0a41-015f-4285-bf8d-aa3850be26bd.png)
 
I'm not familiar with Straight. Is it possible that the way you tested is not correct because the directory actually didn't have the executable? -- therefore, your Org-roam in the test Emacs didn't store anything in the database.

Can you remove Straight out of the equation?

**Comment by reteo** [comment] 2022-04-25 21:12
For Straight, the executables are all placed in the directory `<emacs-config-directory>/straight/build` after compilation.  You should see them in the first two screenshots above.

That being said, I wiped it all out of the test folder and used Emacs's default package manager.  It installed everything needed, and ran fine.  Again, it made and saved the nodes, and saved their IDs, but it did not find them, and typing the exact name once again just generated a new copy of the same node with a new ID (I had both in separate buffers and compared them).
![dual test nodes - 2022-04-25 @ 17-12-33](https://user-images.githubusercontent.com/11682197/165175901-3820b8f2-c7a1-47d3-a42a-615b76c3d154.png)

**Comment by nobiot** [comment] 2022-04-26 06:24
Hmm... 

It might be worth taking a step back, slow down a bit, and check each step more carefully.
Particularly, I was not sure if you had `org-roam-db-autosync-mode` active in the last try without Straight.

Here is what I have done after seeing your last response.

1. In my file manager, delete `~/.config/emacs` directory
2. In my file manager, delete and create a new directory `~/org-roam` (default Org-roam directory)
3. Launch Emacs (this opens vanilla Emacs with no configuration)
4. Quit the splash screen by pressing "q" to move to the scratch buffer. 
5. Paste the following lines to the scratch buffer
 ```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-refresh-contents)
(package-install 'org-roam)

(org-roam-db-autosync-mode 1)
(global-set-key (kbd "C-c n /") #'org-roam-node-find)
```
6. Do `M-x eval-bffer` as shown in the screen shot below. 
    This starts installation of org-roam. While Emacs is at it, you will also see a message saying `emacsql-sqlite` is being compiled

![Screenshot from 2022-04-26 07-59-44](https://user-images.githubusercontent.com/12507865/165232288-ce8bfe93-43fe-4fa4-b5eb-5f1b5e1eab38.png)

7. Call `org-roam-node-find` (in my case, `C-c n /` but it can be via `M-x org-roam-node-find` and create two test nodes
    Make sure I save the buffer after I created them

![Screenshot from 2022-04-26 08-01-14](https://user-images.githubusercontent.com/12507865/165232298-7f5e582f-ef1c-4054-8605-b39b710a1cb2.png)

8. After I have created two nodes, Call `org-roam-node-find`, type "test" and press `TAB` -- this opens the completion buffer and shows the two nodes I created in step 7

![Screenshot from 2022-04-26 08-01-58](https://user-images.githubusercontent.com/12507865/165232312-267f894e-beb4-41ee-97a1-30de1fbdb697.png)

**Comment by nobiot** [comment] 2022-04-26 17:07
@reteo For Org-roam, we are on the same code base -- whether you use `package.el` or `straight`. It's confusing because `org-roam-version` uses different parts of the code base to display the version. If there is `.git` directory, it will look at the git [tag](https://github.com/org-roam/org-roam/releases/tag/v2.2.2), which is v2.2.2; if not, it will look at the [source header](https://github.com/org-roam/org-roam/blob/main/org-roam.el#L8), which is still v2.2.1.

Just to prove we are using the same source code, in my Emacs installation I have this [line of code ](https://github.com/org-roam/org-roam/commit/e8b4822a859ef5d2f2b5b33a4ee3c8c2a3b73d1d#diff-3036732348b94bb14f93f222aa3711f1663b0d90a84154e9f67f78dd5ef35437R556) from the second from the last commit; the [last commit](https://github.com/org-roam/org-roam/commit/b63ff2a7bbd888128939b8ae88c3f62c0d529945) does not change the source code but only change log, so not relevant (and MELPA does not package it).

I don't see how Straight works, but I'm not really convinced that it's working to your favour in this occasion. Your `init.el` does not seem to be used -- by the looks of how `package.el` downloaded the packages, `user-emacs-directory` set in `init.el` does not seem to be used in your test run (it seems to be set to `~/.emacs.d` as the packages are installed in `~/.emacs.d/elpa`, not `~/.emacs.test.d`).

```
;; This is a test configuration.  Let's use the test directory.

(setq user-emacs-directory "~/.emacs.test.d/")
```
To me,  it's either `straight` or `org 9.5.3` -- I have successfully used some version of 9.6 so you might like to upgrade your org. But I suggest you might like to look at `straight` more critically.

**Comment by nobiot** [comment] 2022-04-26 17:11
Nope. Org 9.5.3 works too. Sorry, my investigation ends here.

**Comment by reteo** [comment] 2022-04-26 18:22
Understood.  Thanks for your time.

**Comment by toregilhk** [comment] 2022-04-28 20:29
Not sure if this will help you; but I found I had what appears to be same issue yesterday.

Took a longer look at it today, and it turns out that the problem (for me at least), was that I had set org-roam-file-exclude-regexp to "data/". The path to my org-roam-directory is "~/data/org-roam/", which caused org-roam to ignore the entire org-roam directory… I changed org-roam-file-exclude-regexp to "org-roam/data/" instead, and now it works again.

**Comment by molekular** [comment] 2022-04-29 09:33
Thank you, this solved it for me too on termux.

**Comment by nobiot** [comment] 2022-04-29 15:41
@toregilhk @molekular @jaavedd9 This is rather specific manual configuration. Is it possible that you all have a common source (blog, YouTube etc.) you all copied from?

**Comment by jaavedd9** [comment] 2022-04-29 19:00
@nobiot the problem is the default value of `org-roam-file-exclude-regexp` "data/", whoever has "data" in the `org-roam-directory` path will face this problem. In my case `org-roam-directory=/mnt/data/..../org_files/org_roam/../`

**Comment by reteo** [comment] 2022-04-29 22:03
Hmmm... that would technically apply to my setup, too, although while the actual path is `~/Data/Synchronization/SyncThing/Organizer/Knowledge`, I use a softlink directly in the homedir that bypasses "Data/Synchronization/SyncThing/" in the path, and in my case, "Data" is capitalized.  I'm not sure how softlinks or capitalization would apply to the issue, however.

**Comment by molekular** [comment] 2022-05-02 15:20
@nobiot I have not touched that value before in my configuration. I had a couple of consecutive installations of org-roam with the exact same configuration, that value seems to have changed at some time, not sure what had set it.

**Comment by nobiot** [comment] 2022-05-02 16:13
@jaavedd9 @toregilhk @molekular Thank you. This makes sense to me now; hopefully @toregilhk’s PR will fix the issue (now pushed by Jethro’

@reteo You use file-truename when you set org-directory in the config you shared above, so it is likely you are affected by the same issue. Try evaluating the line in your config.

**Closed** 2022-05-02 16:12 UTC

**Comment by jethrokuan** [comment] 2022-05-02 16:14
Thanks for providing support as always @nobiot , appreciate it.
