### ISSUE TITLE
Error when running in batch mode : wrong-type-argument window-live-p nil

### ISSUE THREAD

**Issue by reyman** [org-roam/org-roam#1151] opened 2020-09-28 13:26 UTC
### Description

Don't know if it's linked to `org-roam` or `doom-emacs`, i'm trying to simply `org-publish` in batch mode with emacs like this : 

`emacs --batch -l ~/.emacs.d/init.el --load publish.el --funcall toggle-debug-on-error --funcall org-publish-all`

My `publish.el` script works (not using org-roam actually...) well when i run from emacs gui mode, but not work when i run in batch mode.

#### Steps to Reproduce

publish.el 

```

(require 'ox-publish)
;; (require 'org-roam)
(require 'ox-html)
(require 'ox-slimhtml)
(require 's)
(require 'dash)

(setq highlight-indent-guides-auto-enabled nil)

(setq make-backup-files nil)
;; this is important - otherwise org-roam--org-roam-file-p doesnt work.
(setq org-roam-directory "/home/reyman/Projets/geoarxiv-dg")

(setq geoarxiv/project-dir "/home/reyman/Projets/geoarxiv-dg")
(setq geoarxiv/publish-dir "/home/reyman/Projets/geoarxiv-dg/_publish")

(setq geoarxiv/preamble "<div><a href='/'>GeoArxiv</a></div>")
(setq geoarxiv/postamble "This page last updated: %C.  <a href='the-map.html'>Map</a>. <a href='sitemap.html'>Index</a>. ")
(setq geoarxiv/head-extra "<link rel='stylesheet' type='text/css' href='css/normalize.css'/>
<link rel='stylesheet' type='text/css' href='css/geoarxiv.css'/>")

(org-export-define-derived-backend 'ox-slimhtml-publish-to-html 'slimhtml
  :translate-alist '((bold . ox-slimhtml-bold)
                     (special-block . org-html-special-block)))

(setq org-publish-project-alist
      `(("geoarxiv"
         :components ("geoarxiv-notes" "geoarxiv-static")) ;
        ("geoarxiv-notes"
         :base-directory ,geoarxiv/project-dir
         :base-extension "org"
         :publishing-directory ,geoarxiv/publish-dir
         :publishing-function ox-slimhtml-publish-to-html
         :recursive t
         :headline-levels 4
         :with-toc nil
         :html-doctype "html5"
         :html-html5-fancy t
         :html-preamble ,geoarxiv/preamble
         :html-postamble ,geoarxiv/postamble
         :html-head-include-scripts nil
         :html-head-include-default-style nil
         :html-head-extra ,geoarxiv/head-extra
         :html-container "section"
         :htmlized-source nil
         :auto-sitemap t
         :sitemap-title "All pages")
        ("geoarxiv-static"
         :base-directory ,geoarxiv/project-dir
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|svg\\|pdf"
         :publishing-directory ,geoarxiv/publish-dir
         :recursive t
         :publishing-function org-publish-attachment)))
       
(defun ngm/republish ()
  (let ((current-prefix-arg 4))
    (call-interactively 'org-publish-all)))

```

`emacs --batch -l ~/.emacs.d/init.el --load publish.el --funcall toggle-debug-on-error --funcall org-publish-all`

#### Backtrace

```
➜ emacs --batch -l ~/.emacs.d/init.el --load publish.el --funcall toggle-debug-on-error --funcall org-publish-all
Package cl is deprecated
Debug on Error enabled globally
Loading /home/reyman/.emacs.d/.local/cache/org-timestamps/geoarxiv-notes.cache...
Generating sitemap for All pages
Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  #<subr select-window>(nil nil)
  ad-Advice-select-window(#<subr select-window> nil)
  apply(ad-Advice-select-window #<subr select-window> nil)
  select-window(nil)
  org-roam-buffer--get-create()
  (save-current-buffer (set-buffer (window-buffer)) (org-roam-buffer--get-create))
  (and +org-roam-open-buffer-on-find-file (memq 'org-roam-buffer--update-maybe post-command-hook) (not (window-parameter nil 'window-side)) (not (eq 'visible (org-roam-buffer--visibility))) (save-current-buffer (set-buffer (window-buffer)) (org-roam-buffer--get-create)))
  +org-roam-open-buffer-maybe-h()
  run-hooks(find-file-hook)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1ff1f3858d2b>)(nil t)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1ff1f3858d2b>) (nil t))
  (if (setq doom-large-file-p (and buffer-file-name (not doom-large-file-p) (file-exists-p buffer-file-name) (condition-case nil (progn (> (nth 7 (file-attributes buffer-file-name)) (* 1024 1024 (assoc-default buffer-file-name doom-large-file-size-alist ...)))) (error nil)))) (prog1 (apply orig-fn args) (if (memq major-mode doom-large-file-excluded-modes) (setq doom-large-file-p nil) (if (fboundp 'so-long-minor-mode) (progn (so-long-minor-mode 1))) (message "Large file detected! Cutting a few corners to impr..."))) (apply orig-fn args))
  doom--optimize-for-large-files-a(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1ff1f3858d2b>) nil t)
  apply(doom--optimize-for-large-files-a #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1ff1f3858d2b>) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer 20200924233210-index.org> "~/Projets/geoarxiv-dg/20200924233210-index.org" nil nil "~/Projets/geoarxiv-dg/20200924233210-index.org" (16023970 64770))
  find-file-noselect("/home/reyman/Projets/geoarxiv-dg/20200924233210-in...")
  org-publish-find-property("/home/reyman/Projets/geoarxiv-dg/20200924233210-in..." :title ("geoarxiv-notes" :base-directory "/home/reyman/Projets/geoarxiv-dg" :base-extension "org" :publishing-directory "/home/reyman/Projets/geoarxiv-dg/_publish" :publishing-function ox-slimhtml-publish-to-html :recursive t :headline-levels 4 :with-toc nil :html-doctype "html5" :html-html5-fancy t :html-preamble "<div><a href='/'>GeoArxiv</a></div>" :html-postamble "This page last updated: %C.  <a href='the-map.html..." :html-head-include-scripts nil :html-head-include-default-style nil :html-head-extra "<link rel='stylesheet' type='text/css' href='css/n..." :html-container "section" :htmlized-source nil :auto-sitemap t :sitemap-title "All pages"))
  org-publish-find-title("/home/reyman/Projets/geoarxiv-dg/20200924233210-in..." ("geoarxiv-notes" :base-directory "/home/reyman/Projets/geoarxiv-dg" :base-extension "org" :publishing-directory "/home/reyman/Projets/geoarxiv-dg/_publish" :publishing-function ox-slimhtml-publish-to-html :recursive t :headline-levels 4 :with-toc nil :html-doctype "html5" :html-html5-fancy t :html-preamble "<div><a href='/'>GeoArxiv</a></div>" :html-postamble "This page last updated: %C.  <a href='the-map.html..." :html-head-include-scripts nil :html-head-include-default-style nil :html-head-extra "<link rel='stylesheet' type='text/css' href='css/n..." :html-container "section" :htmlized-source nil :auto-sitemap t :sitemap-title "All pages"))
  #f(compiled-function (a b) #<bytecode 0x15932fa05f71>)("/home/reyman/Projets/geoarxiv-dg/20200924233210-in..." "/home/reyman/Projets/geoarxiv-dg/interviews/durand...")
  sort(("/home/reyman/Projets/geoarxiv-dg/interviews/" "/home/reyman/Projets/geoarxiv-dg/interviews/202009...") #f(compiled-function (a b) #<bytecode 0x15932fa05f71>))
  org-publish-sitemap(("geoarxiv-notes" :base-directory "/home/reyman/Projets/geoarxiv-dg" :base-extension "org" :publishing-directory "/home/reyman/Projets/geoarxiv-dg/_publish" :publishing-function ox-slimhtml-publish-to-html :recursive t :headline-levels 4 :with-toc nil :html-doctype "html5" :html-html5-fancy t :html-preamble "<div><a href='/'>GeoArxiv</a></div>" :html-postamble "This page last updated: %C.  <a href='the-map.html..." :html-head-include-scripts nil :html-head-include-default-style nil :html-head-extra "<link rel='stylesheet' type='text/css' href='css/n..." :html-container "section" :htmlized-source nil :auto-sitemap t :sitemap-title "All pages") "sitemap.org")
  org-publish-projects((("geoarxiv" :components ("geoarxiv-notes" "geoarxiv-static")) ("geoarxiv-notes" :base-directory "/home/reyman/Projets/geoarxiv-dg" :base-extension "org" :publishing-directory "/home/reyman/Projets/geoarxiv-dg/_publish" :publishing-function ox-slimhtml-publish-to-html :recursive t :headline-levels 4 :with-toc nil :html-doctype "html5" :html-html5-fancy t :html-preamble "<div><a href='/'>GeoArxiv</a></div>" :html-postamble "This page last updated: %C.  <a href='the-map.html..." :html-head-include-scripts nil :html-head-include-default-style nil :html-head-extra "<link rel='stylesheet' type='text/css' href='css/n..." :html-container "section" :htmlized-source nil :auto-sitemap t :sitemap-title "All pages") ("geoarxiv-static" :base-directory "/home/reyman/Projets/geoarxiv-dg" :base-extension "css\\|js\\|png\\|jpg\\|gif\\|svg\\|pdf" :publishing-directory "/home/reyman/Projets/geoarxiv-dg/_publish" :recursive t :publishing-function org-publish-attachment)))
  org-publish-all(nil)
  funcall-interactively(org-publish-all nil)
  call-interactively(org-publish-all nil nil)
  command-execute(org-publish-all)
  command-line-1(("-l" "/home/reyman/.emacs.d/init.el" "--load" "publish.el" "--funcall" "toggle-debug-on-error" "--funcall" "org-publish-all"))
  command-line()
  normal-top-level()

```

### Environment

Copy info below this line into issue:

```
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2020-08-26
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/reyman/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.1
```

**Comment by jethrokuan** [comment] 2020-11-13 06:42
With the changes to the ID link face, all these `window-live-p` errors should now be gone. Closing this issue, feel free to reopen if it still happens.

**Closed by jethrokuan** 2020-11-13 06:42 UTC
Labels: bug

**Comment by reyman** [comment] 2021-01-08 17:32
I there, i'm retrying with the latest version of doom / org-roam, with the same error : 

```
Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  #<subr select-window>(nil nil)
  ad-Advice-select-window(#<subr select-window> nil)
  apply(ad-Advice-select-window #<subr select-window> nil)
  select-window(nil)
  org-roam-buffer--get-create()
  (save-current-buffer (set-buffer (window-buffer)) (org-roam-buffer--get-create))
  (and +org-roam-open-buffer-on-find-file (memq 'org-roam-buffer--update-maybe post-command-hook) (not (window-parameter nil 'window-side)) (not (eq 'visible (org-roam-buffer--visibility))) (save-current-buffer (set-buffer (window-buffer)) (org-roam-buffer--get-create)))
  +org-roam-open-buffer-maybe-h()
  run-hooks(find-file-hook)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fcd2500a97f>)(nil t)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fcd2500a97f>) (nil t))
  #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fcd2500a97f>) doom-first-buffer-hook-h)(nil t)
  apply(#f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fcd2500a97f>) doom-first-buffer-hook-h) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer 20201208173127-index_gtd.org> "~/Notes/2ndBrain/20201208173127-index_gtd.org" nil nil "~/Notes/2ndBrain/20201208173127-index_gtd.org" (17618593 64770))
  find-file-noselect("20201208173127-index_gtd.org" nil nil nil)
  find-file("20201208173127-index_gtd.org")
  org-babel-tangle-file("20201208173127-index_gtd.org" "20201208173127-index_gtd.el" "emacs-lisp\\|elisp")
  org-babel-load-file("20201208173127-index_gtd.org")
  eval-buffer(#<buffer  *load*> nil "/home/reyman/Notes/2ndBrain/gtd.el" nil t)  ; Reading at buffer position 185
  load-with-code-conversion("/home/reyman/Notes/2ndBrain/gtd.el" "/home/reyman/Notes/2ndBrain/gtd.el" nil t)
  load("/home/reyman/Notes/2ndBrain/gtd.el" nil t)
  command-line-1(("-l" "/home/reyman/.emacs.d/init.el" "--funcall" "toggle-debug-on-error" "-l" "/home/reyman/Notes/2ndBrain/gtd.el"))
  command-line()
  normal-top-level()

Cleaning up the recentf list...
File ~/Notes/GTD/projects/rzine.org removed from the recentf list
File ~/Notes/GTD/projects/MAPSmodels.org removed from the recentf list
File ~/Notes/GTD/projects.org removed from the recentf list
File ~/Projets/git-conflict-game/world.py removed from the recentf list
Cleaning up the recentf list...done (4 removed)
```

**Comment by reyman** [comment] 2021-01-08 20:48
@jethrokuan Found a similar bug here, if that could help you to debug : 
https://github.com/yuya373/emacs-slack/issues/438

**Comment by amatsukawa** [comment] 2021-02-07 21:21
I think the problem is this line the doom-emacs configuration of org-roam

https://github.com/hlissner/doom-emacs/blob/16a495c97dd796ec20939d07bad3beb38586a1fe/modules/lang/org/contrib/roam.el#L71

**Comment by benmezger** [comment] 2021-03-07 14:03
> I think the problem is this line the doom-emacs configuration of org-roam
> 
> https://github.com/hlissner/doom-emacs/blob/16a495c97dd796ec20939d07bad3beb38586a1fe/modules/lang/org/contrib/roam.el#L71

That is correct. I temporarily fixed this by adding the following to my publish.el `(remove-hook! 'find-file-hook #'+org-roam-open-buffer-maybe-h)`

**Comment by hanschen** [comment] 2021-04-09 08:37
I also have this issue unless I add @benmezger's fix. Should this issue be re-opened?

**Comment by jethrokuan** [comment] 2021-04-09 09:26
> I also have this issue unless I add @benmezger's fix. Should this issue be re-opened?

This is not something caused by Org-roam, nor is it fixable on this end.
