### ISSUE TITLE
[FEATURE] Link to org-mode Headlines

### ISSUE THREAD

**Issue by wakatara** [org-roam/org-roam#548] opened 2020-05-01 18:02 UTC
### Brief Abstract

Extend org-roam to allow linking to a org-mode headline within a file rather than just a file name. 

### Long Description

Org-mode's greatest asset is the representation of hierarchical information defined by headlines. Most files are organized in a way to make that the quantum of information and both org-mode links and similar allow direct linking and follow to those. 

Why? 
This would allow both more relevant information used by other programs (org-contacts etc) to be utilized more effectively, For example, structured formats which are used by other programs to provide functionality could be folded in and org-roam used as a semantic layer above that 
(for example: CRM. org-contact used to provide structured info, thta is linked to a page for each person... even more interestingly, perhaps programatically info could be embedded in an org-roam page from those sources via some sort of literate programming - for example, I'd love to see the contact info represented in a nice form, but say it have a complete log of all interactions with them across various backlinks and dates. 

### Proposed Implementation (if any)

As an example of how it might work with ivy completion in org-roam, I'd look at the org-mode has a Refile functionality (C-c C-w on my machine) which allows reflling of headlines both in pages and *under* headlines. Roam would be amazingly better, if rather than using the file as the quantum of info, it used the headline.

### Please check the following:
- [X ] No similar feature requests
I did search in the Issues but saw nothing

**Comment by alan-carroll** [comment] 2020-05-01 19:06
FWIW at first I wanted the same functionality, but the more I have been thinking about it I am not certain that it is a good idea. It would be a lot of code and logic to add and rewrite and doesn't fit well with the intention of the package (as I see it, at least), when the alternative it to just use a standard org-link in the places you want it.

In your contacts example, your contacts.org file could sit in your org-roam dir as an 'index' note that both had org-contact structural information AND an org-roam link to a separate per-person note. The backlink from the per-person note already links back to the content in contacts.org (if you click it I think -- perhaps this could be made easier). If you need something more specific still, it is trivial to add a standard header link in either location.

If you still need more aggregation, as you say you can do a literate code block or even write an elisp function that you can call through an org link. The backlinks buffer would already populate with all references from daily notes/interactions you record in org-roam on the per-person note; it would be easy to filter these out in some way as a list of results under their contact header in your contacts.org. I think adding some documentation and/or helper functions for these types of actions would be helpful for users uncomfortable with digging through code themselves.

Like I said I really wanted this when I started, but I think I just had the wrong perspective of how to fit things together. Can you think of other examples where you would really need to have org-roam link to headers? If it already did, I'm sure people would come up with interesting uses, but I started to change my mind because I couldn't identify a situation that NOT linking to headers was really going to make anything difficult for me. I just might have to write a function or two in specific edge cases, but that will be true no matter what.

**Comment by kbruskiewicz** [comment] 2020-05-01 19:49
You can probably use `org-brain` for this.

**Comment by zaeph** [comment] 2020-05-01 21:08
I'm not sure if this is a good idea.

Org-roam is about inter-relating concepts, and we use files as the unit of meaning.  The reason why we elected to use files instead of headings in a large file is that the latter become unwieldy once it reaches a certain stage.  There are many packages that could help you find headings in a set of files such as [`helm-org-rifle`](https://github.com/alphapapa/org-rifle).

I'm not sure if I understand exactly what you are trying to do with your contacts, but it seems that you're trying to do something with Org-roam that it wasn't designed to do.  Could you describe how exactly would your workflow benefit from having backlinks?

-----

#### A little aside on file/headings paradigms

I think this harks back to the usual clash between two paradigms:
- Few large files, the headings of which are accessed via `org-refile`.
- Many small files which are accessed via complexifications of `find-file`.

It's a discussion that often crops up on Reddit, and you can find a lot of blog-posts about it.  The usual conclusion is that large files quickly become unwieldy, especially when you need to explore them when the headings are folded.  Some projects are on the way to resolve those issues, but it's unlikely that a solution will be found in the near future due to the amount of work required.

Small files, on the other hand, do not present as many problems.  You might be thinking that this workflow makes it hard to access items, but there are plenty of tools to help you do that like .  Once you develop an expertise with the Org-mode internals, it also becomes possible to design really advanced workflow.

> Org-mode's greatest asset is the representation of hierarchical information defined by headlines. Most files are organized in a way to make that the quantum of information and both org-mode links and similar allow direct linking and follow to those.

I'm not sure if this is Org-mode greatest asset.  The headings are nice, don't get me wrong, and they allow for some pretty neat stuff, e.g., smooth navigation via folding, jumping, linking, etc.  But I would argue that Org-mode greatest asset is the fact that it provides both a sane standard for note-taking as well as extensive libraries to programmatically process them (think `org-agenda`).

**Comment by wakatara** [comment] 2020-05-02 07:48
I was surprised this garnered the response it did. Love the thoughts and discussion though. Thanks as I had not considered the many small files, loosely linked use case but find the mental model we must all have in our heads about information and organizing it is super interesting (and the crux of this ticket besides the complexity of adding the feature.).

And apologies, @zaeph , I have to admit I was honestly unaware there was a "many, small"/"few, big" debate on how to organize your files (I'm both: small files like dailies but big files aggregating areas of responsibilities or projects or over big concepts like goals and long stretches of time (years)).

Without too philosophical a debate, the advantage of org-mode (to me) is not so much the standard (markdown does this tho presentation focused and was fine) as it's ability to structurally better represent a knowledge graph hierarchically in a file and it parses certain info via libraries as you say (tbh, org-agenda is what drew me to the dark side 2 years ago =p  - but I'd argue you could do the same with markdown given keywords -- and in fact, actually prefer its stylistic conventions like code fences and quotes better for representing src and quotes than the `#+` thing.)

However, the issue is then info/notes are siloed under how it was captured and structured originally. It cannot be cross-linked easily from the file (tags sorta get you there, but org-roam seems a better concept and love bi-directional backlinks idea in the Roam web app.). 

As a model though, org-roam emulates a wiki where right now it links to wiki pages, but not headings in each of the pages (take as an example, wikipedia, which links to both pages and headings). So, for me the big value is to deeper link *into* various knowledge graphs rather than at top level capture (which are not always topics). Admittedly, this has probably more to do with my workflow and organization, as you suggest (for example, I take notes on books, I would link into topics at a level in the note rather than at the level of the book title generally)

The value of org-roam to me is to break into the silos rather than just refer to them. Re-organize and "re-see" the knowledge graph if you will, especially where I might have organized them differently (or poorly) originally. I am sort of experimenting with it from a CRM and GTD perspective at the moment, which is where the request came from.

YMMV, though as you say it might be depending on how you collect and use information. I also have to admit I did not realize it would make the code base so much more complex, as you say org-mode already has the ability to copy and link to headings (I do it all the time) so had assumed it was just not something that had had time to be developed. (and really loved the idea of those being available via backlink to me... =] ). Having an interface like the `org-mode refile` one to select those headings was more useful to me than just the wiki page selection (which weirdly, I mostly use for refiling things from my inbox to the days' and headings in question.).

*(btw, great convo. I hope I've made myself better understood here since I feel I wrote poorly in the original request... note to self: do not file tickets at 4am SG time... =p  I honestly thought I was asking for a no-brainer that was uncontentious.).*

**Comment by zaeph** [comment] 2020-05-02 10:56
> I was surprised this garnered the response it did. Love the thoughts and discussion though. Thanks as I had not considered the many small files, loosely linked use case but find the mental model we must all have in our heads about information and organizing it is super interesting (and the crux of this ticket besides the complexity of adding the feature.).

The discussions about method are essential to develop a good UX, so thank you for bringing it up.

> And apologies, @zaeph , I have to admit I was honestly unaware there was a "many, small"/"few, big" debate on how to organize your files (I'm both: small files like dailies but big files aggregating areas of responsibilities or projects or over big concepts like goals and long stretches of time (years)).

No need to apologise.  I mentioned it to give you a pointer towards further reflection on the topic.

> However, the issue is then info/notes are siloed under how it was captured and structured originally. It cannot be cross-linked easily from the file (tags sorta get you there, but org-roam seems a better concept and love bi-directional backlinks idea in the Roam web app.).

Just to be clear, aside from the commands to smooth out the UX, everything is already there to allow backlinks to specific headings.

If, in the `org-roam-buffer` (i.e. the side-window accessible with `M-x org-roam`), you click on the context where a link was found rather than on the link, you will be brought to that context.  Here’s a demo:

![output-2020-05-02-12:20:03](https://user-images.githubusercontent.com/12202828/80862195-4c73b300-8c73-11ea-8bef-ce2793c5d524.gif)

Now, if you want to a specific heading, you can just use the regular `org-store-link` on the destination of the link, go back to the other file, and insert that link with `org-insert-link`.  Here’s another demo:

![test-2](https://user-images.githubusercontent.com/12202828/80862325-5cd85d80-8c74-11ea-8000-f21b94f9effd.gif)

> As a model though, org-roam emulates a wiki where right now it links to wiki pages, but not headings in each of the pages (take as an example, wikipedia, which links to both pages and headings). So, for me the big value is to deeper link _into_ various knowledge graphs rather than at top level capture (which are not always topics). Admittedly, this has probably more to do with my workflow and organization, as you suggest (for example, I take notes on books, I would link into topics at a level in the note rather than at the level of the book title generally)

I think this is valid, and not specific to your workflow.  However, as discussed in Ahrens (2017), we should guard ourselves from associating slip-boxes and wikis: the latter imply exhaustiveness whereas the former imply organicity (hence ‘roaming’ rather than ‘map out everything’).  I heartily recommend you to explore the book if you’re interested.

> The value of org-roam to me is to break into the silos rather than just refer to them. Re-organize and "re-see" the knowledge graph if you will, especially where I might have organized them differently (or poorly) originally. I am sort of experimenting with it from a CRM and GTD perspective at the moment, which is where the request came from.

I prefer to keep my organisation away from my knowledge-related notes.  I don’t find that the former benefit from having backnotes in my workflow since my system is built on atomic tasks which are pruned whenever they’re not actual anymore.  Personally, I use two elaborates setup to access my notes: one with a [`hydra`](https://github.com/abo-abo/hydra), one with auto-generated `org-agenda` custom-views.  All this happen in a single file, but it took a long time to optimise it, and I would not recommend anyone go through the trouble of doing it that way.

> YMMV, though as you say it might be depending on how you collect and use information. I also have to admit I did not realize it would make the code base so much more complex, as you say org-mode already has the ability to copy and link to headings (I do it all the time) so had assumed it was just not something that had had time to be developed. (and really loved the idea of those being available via backlink to me... =] ). Having an interface like the `org-mode refile` one to select those headings was more useful to me than just the wiki page selection (which weirdly, I mostly use for refiling things from my inbox to the days' and headings in question.).

The complexity lies in validating the links.  We’re running plenty of functions in the background to prevent the corruption of the db and for maintaining the links consistent between files.  Doing the same thing for headings would be quite hard.  Org-mode provides a facility for generating `:ID:` property which alleviate the problem, but the problem is that it requires a table listing mapping files to `:ID:` which scales poorly.  Org-brain attempted to do it, and I don’t think it had much success.  We could implement this into the database, but that’s where the complexity I’d envisioned would lie.

If we do not care about validating the links, the only thing we need is a modified behaviour to `org-roam-insert` (accessible via a `C-u` argument) which would first prompt you for the files, and _then_ prompt you for the heading.  However, I think this pales in comparison to simply storing/pasting the link using Org-mode’s defaults.

Also, I’ve just noticed that we’re not updating the links when they’re in the format `file:ahrens2017.org::*Heading`.  This should be trivial to fix, though.

> _(btw, great convo. I hope I've made myself better understood here since I feel I wrote poorly in the original request... note to self: do not file tickets at 4am SG time... =p I honestly thought I was asking for a no-brainer that was uncontentious.)._

You did.  Thanks you for bringing up those points.

References:
<div class="csl-bib-body" style="line-height: 1.35; margin-left: 2em; text-indent:-2em;">
  <div class="csl-entry">Ahrens, Sönke. <i>How to Take Smart Notes: One Simple Technique to Boost Writing, Learning and Thinking for Students, Academics and Nonfiction Book Writers</i>, 2017.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=urn%3Aisbn%3A978-1-5428-6650-7&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=How%20to%20Take%20Smart%20Notes%3A%20One%20Simple%20Technique%20to%20Boost%20Writing%2C%20Learning%20and%20Thinking%20for%20Students%2C%20Academics%20and%20Nonfiction%20Book%20Writers&amp;rft.aufirst=S%C3%B6nke&amp;rft.aulast=Ahrens&amp;rft.au=S%C3%B6nke%20Ahrens&amp;rft.date=2017&amp;rft.isbn=978-1-5428-6650-7&amp;rft.language=English"></span>
</div>

**Comment by bdarcus** [comment] 2020-05-03 17:32
It occurs to me we could use something like this section of a similar package somewhere prominent in the readme and/or docs; a clear high-level description of the model upfront?

https://www.eliasstorms.net/zetteldeft/#org9890853

**Comment by bernardjosef** [comment] 2020-05-10 07:20
I would also argue in favor of link to headlines and I use it in the `org-store-link` and `org-insert-link` way. For me it is more convenient, e. g. when I write notes about a book I read, to do it in one single file with different headings. Of course I can do this in several files and link them together, but then the original line of thoughts gets lost a bit. Maybe this has something to do with the different opinions about the relevance of the so called »Folgezettel« of Luhmanns Zettelkasten, as discussed e. g. in https://zettelkasten.de/posts/luhmann-folgezettel-truth.

> The complexity lies in validating the links. We’re running plenty of functions in the background to prevent the corruption of the db and for maintaining the links consistent between files. Doing the same thing for headings would be quite hard.

Does this mean that it has to be checked if all headings which occur in links are valid? I do not think that this is necessary. In my understanding, org links with search options, such as `file:ahrens2017.org::*Heading`, but also `file:ahrens2017.org::10` etc., are already handled by org-roam correctly and shown as backlinks in the backlinks buffer. Or has there be something to be fixed in the database code?

> If we do not care about validating the links, the only thing we need is a modified behaviour to `org-roam-insert` (accessible via a `C-u` argument) which would first prompt you for the files, and then prompt you for the heading. However, I think this pales in comparison to simply storing/pasting the link using Org-mode’s defaults.

Thus there is only a thing in `org-roam-insert` to be implemented. I tried that and it seems to work quite well. And what is meant by

> Also, I’ve just noticed that we’re not updating the links when they’re in the format `file:ahrens2017.org::*Heading`. This should be trivial to fix, though.

Is it the function `org-roam--rename-file-advice`, where org links with search options are not handled properly?

**Comment by zaeph** [comment] 2020-05-10 08:01
> Does this mean that it has to be checked if all headings which occur in links are valid? I do not think that this is necessary. In my understanding, org links with search options, such as `file:ahrens2017.org::*Heading`, but also `file:ahrens2017.org::10` etc., are already handled by org-roam correctly and shown as backlinks in the backlinks buffer. Or has there be something to be fixed in the database code?

> Is it the function `org-roam--rename-file-advice`, where org links with search options are not handled properly?

Yes.  The problem is that those `file+heading` links are not updated properly.  Note even the `file`-part of the link gets modified right now, which should be trivial to fix (although we'd need to modify `org-roam-doctor`'s fixes as well, now).  However, we have no way to validate whether the heading actually exists, and so, if it is modified, upon opening the link, you'd be asked to create that heading.  Org-mode handles it with UUIDs stored in a table, but it is redundant with our own db.

One way we could do it would be to use the `org-id` infrastructure to create the UUID for the heading, but on top of storing/retrieving it in the vanilla Org-mode way (for compatibility), we implement this in the DB.  Links to heading would have an extra `uuid` value which we could use to resolve the links.

Then, we'd have to handle `file:` like and `id:` links differently, and create the whole infrastructure for validating them.  It's a lot of work, but it could be doable.  I think I'll tackle this within the fortnight.

**Comment by bernardjosef** [comment] 2020-05-10 08:16
> However, we have no way to validate whether the heading actually exists, and so, if it is modified, upon opening the link, you'd be asked to create that heading.

I do not see the point in validating all headings upon modification. Otherwise it must be seen as a bug in org-roam already, as it is always possible to create a link with heading somehow and later modify the heading thereby making the link invalid. In my opionion it is sufficiant to validate the file name.

> One way we could do it would be to use the org-id infrastructure to create the UUID for the heading, but on top of storing/retrieving it in the vanilla Org-mode way (for compatibility), we implement this in the DB. Links to heading would have an extra uuid value which we could use to resolve the links.

I do not think that it is a good idea to have an extra ID in each heading. I tried out org-brain previously but was not convinced.

**Comment by zaeph** [comment] 2020-05-10 08:27
> I do not see the point in validating all headings upon modification. Otherwise it must be seen as a bug in org-roam already, as it is always possible to create a link with heading somehow and later modify the heading thereby making the link invalid. In my opionion it is sufficiant to validate the file name.

By 'validating', I meant making sure that the link points to a valid destination.  Since we're already doing this in the background for file-names, if we officially support `file+headline` links, it'd warrant validating those links as well.

> I do not think that it is a good idea to have an extra ID in each heading. I tried out org-brain previously but was not convinced.

We would not be creating a UUID for every heading, just for those that would need to be linked too.  If you're worried about the proliferation of `:PROPERTIES:`, we could have `org-roam-doctor` garbage-collect the UUIDs which aren't used as a destination anywhere.

**Comment by zaeph** [comment] 2020-05-16 22:17
#648 improved the renaming of links on file-moves, to the point where it is now very robust.  Coupled with `org-roam-doctor`, we're starting to get pretty a pretty good setup.

The next logical step is to support links to headlines with the implementation I've detailed above.  I'll start work on this next week.

**Comment by bdarcus** [comment] 2020-05-17 12:19
So @zaeph - above you said you were skeptical about this. As am I.

Am I to conclude you changed your mind? If yes, why?

Have you figured out how to address your (legitimate) concerns about UX?

**Comment by jethrokuan** [comment] 2020-05-17 13:08
We haven't thought this through properly yet, but I do want to support headline linking, with a decent UX at least at first headline level.

One reason why I want to support this that at least for bibliographic notes with an appropriate source, notes from `org-noter` are captured at the second headline level. It would be useful for me at least, to be able to easily link to specific note from the source, rather than the source itself.

One simple implementation would be to have a variable `org-roam-targets`, similar to `org-refile`, which specifies the possible targets. We cache all possible headline links and present them in `org-roam-insert`.

When inserting a link to a headline, we can generate an org-id for that headline, and cache org-id links in our links db.

It all seems doable at first-glance, but I'm still wondering if we want to do this, or have something like org-noter that captures the notes into different files (using the `ROAM_KEY` to know where the notes are) would be a cleaner and more forward-looking solution that's more consistent with the zettelkasten standard.

**Comment by bdarcus** [comment] 2020-05-17 14:46
> I'm still wondering if we want to do this, or have something like org-noter that captures the notes into different files (using the `ROAM_KEY` to know where the notes are) would be a cleaner and more forward-looking solution that's more consistent with the zettelkasten standard.

Not sure I follow here; you mean to have multiple `ROAM_KEYS` for each source? For sake of illustration `doe18` and `doe18#p4`?

Or something else?

**Comment by zaeph** [comment] 2020-06-08 09:29
I'm finally able to have a go at this, so expect news by the end of the week.

**Closed** 2020-06-12 10:51 UTC
Labels: enhancement, priority/p2, status: in progress
