### ISSUE TITLE
Slowness when storing a file with lots of links

### ISSUE THREAD

**Issue by zecevicp** [org-roam/org-roam#1824] opened 2021-09-01 05:19 UTC
### Description

If a file has a large number of links (of any type), org-roam takes a very long time to save the buffer (tens of seconds) because it is parsing the buffer, finding all the links and saving them as backlinks to the database. However, I don't see why should http:, https:, and file: links go into the database. In other words, I think this is a bug. 

So I'm proposing the following simple change to the `org-roam-db-insert-link` function so that it only stores "id" links:

```(defun org-roam-db-insert-link (link)
        "Insert link data for LINK at current point into the Org-roam cache."
        (save-excursion
          (goto-char (org-element-property :begin link))
          (let ((type (org-element-property :type link)))
            (if (string= "id" type)
              (let ((dest (org-element-property :path link))
                      (properties (list :outline (org-get-outline-path)))
                      (source (org-roam-id-at-point)))
                (when source
                  (org-roam-db-query
                     [:insert :into links
                        :values $v1]
                      (vector (point) source dest type properties))))))))
```

It would still be slow if one had lots of id connections in a file, but I believe that is a rare case.

**Comment by Wetlize** [comment] 2021-09-01 10:44
> In other words, I think this is a bug.

No, it's a feature. There's solution that we have in mind for #1752, but it requires from us to get some other things done first. In any case, I'm closing this, since the issue is clearly a duplicate of #1752, so please, keep all the related things there.

**Closed by Wetlize** 2021-09-01 10:44 UTC
Labels: duplicate, 2. perf
