### ISSUE TITLE
Any change on how org-roam-tag-sources works?

### ISSUE THREAD

**Issue by tareefdev** [org-roam/org-roam#1437] opened 2021-02-23 15:51 UTC
I have `(setq org-roam-tag-sources '(prop vanilla)` in my config file, and it was working fine, until a recent update, where tags on files are no more considered as tags by org-roam.

Thus, if I put `#+TAGS: todo` or `#+FILETAGS: todo` on the top of a file, I'm no longer able to find this file based on its tags.

**Comment by jethrokuan** [comment] 2021-02-26 06:00
Duplicate of #1119. In v2 #1401 , tags will only be pulled from Org tags anyway.

**Comment by jethrokuan** [comment] 2021-06-19 08:17
Fixed in #1520

**Closed by jethrokuan** 2021-06-19 08:17 UTC
