### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by edoloughlin** [org-roam/org-roam#803] opened 2020-06-12 16:38 UTC
### Description

I installed org-roam in Emacs 26.3 on windows using the `use-package` instructions from the readme.

When I M-x org-roam I see an error:

    Cannot open load file: No such file or directory, org-roam
 
No additional buffer

#### Steps to Reproduce

Install in Emacs in windows, run M-x org-roam

#### Backtrace

No backtrace produced

### Environment

_Please M-x org-roam-diagnostics and paste results here_

org-roam-diagnostics doesn't exist.

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by zaeph** [comment] 2020-06-12 16:39
Have you initialised the packages?  See [MELPA's 'Usage' section](https://github.com/melpa/melpa#usage).

**Comment by progfolio** [comment] 2020-06-12 16:46
Likely a duplicate of: #755, #697, #582 

Please search for similar issues when creating a new one.

**Comment by edoloughlin** [comment] 2020-06-12 17:00
Thanks for the suggestion, but these don't seem to help. I installed via use-package. I've used use-package for quite some time and install all my other packages with it, so I don't think initialisation is the problem.

**Comment by progfolio** [comment] 2020-06-12 17:06
Does adding an `:ensure t` to your use-package declaration help?

**Comment by edoloughlin** [comment] 2020-06-13 21:24
Yes it does! Thanks. Don't know why I didn't spot it.

**Closed** 2020-06-13 21:27 UTC
Labels: support, tag: duplicate, waiting-for-reply
