### ISSUE TITLE
org-roam-capture-ref-templates with empty-lines option should not make head content empty

### ISSUE THREAD

**Issue by tshu-w** [org-roam/org-roam#992] opened 2020-07-31 03:51 UTC
### Brief Abstract
org-roam-capture-ref-templates with the empty-lines option should not make head empty.

### Long Description
If I have the following template:
```
("a" "annotation" plain (function org-roam-capture--get-point)
           "${body}\n"
           :file-name "${slug}"
           :head "#+title: ${title}\n#+roam_key: ${ref}\n"
           :immediate-finish t
           :unnarrowed t
           :empty-lines 1)
```
When I run the first time and the corresponding file doesn't exist, the head will be inserted with empty lines above. I think empty lines should be inserted after head and above content.

<img width="1380" alt="Screen Shot 2020-07-31 at 11 48 51 AM" src="https://user-images.githubusercontent.com/13161779/88998225-1f8f7480-d324-11ea-960f-fa0f3941a9e2.png">

### Please check the following:

- [x] No similar feature requests

**Comment by zaeph** [comment] 2020-07-31 05:55
I can confirm this.  Investigating.

**Comment by zaeph** [comment] 2020-07-31 06:03
Can you describe the behaviour that you want?

If you only want to have an empty line between the header and the content, just hardcode an extra `\n` in your `:header` definition.

If you want to have actual `'entry` captures with `org-roam-protocol`, it's not something that is supported.  I'd argue it's better to be dropped *inside* the file on subsequent visits to a created note rather than just having a capture narrowed to a plain or entry addition.

**Comment by tshu-w** [comment] 2020-07-31 06:24
@zaeph In fact, I try to use org-roam for web annotation. If I select something on a web page and then click on a bookmark, the content that I highlight will be captured in the corresponding file. If I repeat the operation multiple times on the same page, the subsequent selections should be appended to the file, separated by blank lines.
here is my bookmarklet:
```
javascript:location.href='org-protocol://roam-ref?template=a&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title%20%7C%7C%20%22%5Buntitled%20page%5D%22)+'&body='+encodeURIComponent(window.getSelection())
```

**Comment by zaeph** [comment] 2020-07-31 06:34
I see.  `org-protocol` is able to achieve this, and we haven't covered that use-case with `org-roam-protocol`.  Since we wrap around `org-capture` to generate those headers, I don't think there's a good way to support `:empty-lines-after` and `-before`.  We're planning to reorganise the way files are created, which implies rethinking the way the header-insertion works.  I'll keep your issue in mind.

**Comment by Wetlize** [comment] 2021-08-11 13:15
I'm pretty sure this whole fiasco was fixed with v2 (where capture implementation is more close to `org-capture`) and subsequent bugfixes for it, so it should now expand the template for the body as expected, separately from and with respect to the `:if-new` target + head, so I'm closing this. Feel free to notify here if this isn't the case, in which case this will be reinvestigated and reopened.

**Closed by Wetlize** 2021-08-11 13:15 UTC
Labels: 1. bug
