### ISSUE TITLE
Migration wizard reported too many open files

### ISSUE THREAD

**Issue by ndw** [org-roam/org-roam#1601] opened 2021-07-18 11:12 UTC
### Description

I have 1,040 files in one of my notes directories. Attempting to run `org-roam-migrate-wizard` fails:

```
Entering debugger...
backtrace--print-to-string: Cannot open load file: Too many open files, cl-print
```

#### Backtrace

There's no back trace, oddly.

### Environment

```
- Emacs: GNU Emacs 27.2 (build 3, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
 of 2021-07-01
- Framework: N/A
- Org: Org mode version 9.4.6 (release_9.4.6-598-g604bfd @ /Users/ndw/.emacs.d/straight/build/org/)
- Org-roam: 2.0.0
```

**Comment by jethrokuan** [comment] 2021-07-18 11:48
Are there any clues as to where it fails? E.g. are the notes in v2 format, but the links still file links?

The wizard actually kills the visiting buffer each time it's done with the file, so that shouldn't really be an issue...

**Comment by ndw** [comment] 2021-07-18 13:34
No, I'm afraid not. I really expected more in the `*Messages*` buffer, to be honest.

I managed to get everything converted by putting groups of files in my Notes folder and translating them in batches then resyncing the database. I don't *know* that this worked correctly, but it seems to have.

(Congratulations on the release, by the way. Org-roam is really great.)

**Comment by jethrokuan** [comment] 2021-07-18 14:54
> (Congratulations on the release, by the way. Org-roam is really great.)

Thanks.

I'm afraid that this could be an OS limitation, I used to see errors like this on my work laptop. I'm going to tag this issue and close it, since there's no actionable right now.

**Closed** 2021-07-18 14:54 UTC
Labels: 1. upstream, 2. migration

**Comment by ndw** [comment] 2021-07-18 15:08
That's fair. Just wanted to let you know.

**Comment by d12frosted** [comment] 2021-07-19 05:43
I faced this issue few months ago, also during some migration of notes (don't think it was related to v2 migration though). And I could not understand, why opening 10k notes leads to this error. After some time of debugging (and reporting file handlers) I realized that it was related to my git configurations that were creating async tasks upon visiting files. I've borrowed an idea of delayed `git-gutter` from Doom Emacs, so if you are using it, chances are it was caused by `git-gutter` configuration in Doom Emacs :)

**Comment by ndw** [comment] 2021-07-19 15:01
I'm not using Doom, but I do have git-gutter enabled, so it could very well have been something to do with that. What's the "delayed git-gutter" fix?

**Comment by fleimgruber** [comment] 2021-08-11 14:19
@d12frosted thanks for the investigation regarding `git-gutter`. I am using Spacemacs, but maybe we can use an approach similar to your idea. Could you please elaborate on that idea a bit?

**Comment by d12frosted** [comment] 2021-08-13 04:54
@fleimgruber unfortunately, I don't really remember all the details, but in the nutshell it was related to usage of `async-start`. So every time a file was opened for migration process, one or more `async-start` was called, and they started to accumulate to the point where I actually was running out of descriptors. I don't remember how exactly I narrowed it down, maybe simply by inspecting threads (e.g. printing them on every step of migration). 🤷 

If you are interested to play with threads, you can use `all-threads` function that returns you the list of all threads. You can print count of threads using something like:

```emacs-lisp
(let ((threads (all-threads)))
  (message
   (concat
    "count of threads: "
    (number-to-string (length threads))
    (when threads "\n")
    (string-join
     (seq-map (lambda (thread)
                (concat "- " (or (thread-name thread)
                                 (and (eq thread main-thread) "Main")
                                 (prin1-to-string thread))))
              threads)
     "\n"))))
```

Example output:

```
count of threads: 2
- Main
- fleimgruber test
```

Ideally there should be only one thread - `Main` 😸 Hope that helps, let me know if you have any other questions.

**Comment by fleimgruber** [comment] 2021-08-13 09:16
@d12frosted thanks for checking back and providing the handy analysis code - already put it into a utility function. Following your lead with `git-gutter`, I am now running with `diff-hl` instead for `version-control-diff-tool` and the error is gone and in general  it feels snappier as a bonus.
