### ISSUE TITLE
Building org-roam.db hangs on Windows

### ISSUE THREAD

**Issue by ahristow** [org-roam/org-roam#1038] opened 2020-08-14 08:45 UTC
### Description
When I delete my org-roam.db or execute `org-roam-db-build-cache` under Windows 7, the process (and therefore Emacs) hangs.

#### Steps to Reproduce
1a. With Emacs closed, delete org-roam.db, the start Emacs.
1b. Alternatively, with Emacs open, issue `org-roam-db-build-cache`.

#### Backtrace

N/A
#### Expected Results
org-roam.db is built within a few seconds, maybe a minute (the file system on my Windows machine is rather slow).

#### Actual Results
An org-roam.db-journal file is created and, if org-roam.db was deleted, a new org-roam.db file is also created. The file system often, but not always, shows the journal file being updated after about 5 minutes. I have let the process run for as long as an hour before killing Emacs, but it never completes.

I do not observe this behavior on my Linux machine, which is running Emacs 26.3 under Ubuntu 20.04 LTS. On that machine, org-roam.db builds within a few seconds. I use the same `init.el` on both machines and the same package configuration, enforced through through the package freeze/thaw functionality of `straight.el`.

### Workaround
Downgrade org-roam to the last official release (org-roam commit: https://github.com/jethrokuan/org-roam/commit/89e9121f26cf03bb7820d257cd9d9106916cd1e9). With this version, org-roam.db successfully builds. I have not tested every commit since this one, so it may also work with other, later commits.

### Environment
- Emacs: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32)
 of 2019-08-29
- Framework: N/A
- Org: Org mode version 9.3.7 (release_9.3.7-708-g5417e3 @ c:/Users/J0398597/AppData/Roaming/.emacs.d/straight/build/org/)
- Org-roam: 1.2.1

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/2081e1268ad57dfb94171d1a99e8f13126fbdaa5

**Comment by beetleb** [comment] 2020-08-26 07:16
I have the same problem. I did not try a prior version, though.

**Comment by beetleb** [comment] 2020-08-27 08:03
I tried cleaning out my files in the directory to see if I could find any pattern. Not 100% sure, but any file that has a http:// in it seems to slow it down (takes several seconds per such file).

It does eventually end, but it takes a long time. Several minutes to do 25 files that I have. Ouch.

**Comment by jethrokuan** [comment] 2020-08-27 10:25
> Not 100% sure, but any file that has a http:// in it seems to slow it down (takes several seconds per such file).

This should have been resolved with #1070

**Comment by j-steinbach** [comment] 2020-08-27 13:54
I also have the same problem. I only have seven files and it takes a long time (never) to finish building the db. 

What I can observe, is that the created db contains many links to websites:

![DB_Browser_for_SQLite_ye4qnSH3Gv](https://user-images.githubusercontent.com/69524139/91450753-2b5f4f80-e86c-11ea-9eff-2a037809b3f9.png)

Furthermore, whenever I edit a file, it lags half a minute. Maybe that is the auto-save? (I am new to Emacs)

I am using Emacs 26 on Windows 10. I tried org-roam both from MELPA (`package install`) and from inside doom `(org +roam)`. My PC has a Ryzen 1700 CPU, 16GB RAM and a SSD.

**Comment by jethrokuan** [comment] 2020-08-27 14:28
@nobiot can you comment here? Are things working for you?

**Comment by beetleb** [comment] 2020-08-27 15:25
Has #1070 been pushed to MELPA?

**Comment by beetleb** [comment] 2020-08-27 15:40
With the latest MELPA (20200827.1413), it takes 169 s to handle 25 files. These are all small files - not many links. I seem to have the changes in #1070

**Comment by jethrokuan** [comment] 2020-08-27 18:02
This issue seems to be Windows specific, I don't have a machine to test it. My 500 files finish in roughly 30s, and the 1000 files in CI take 50s.

**Comment by beetleb** [comment] 2020-08-28 01:03
Does anyone know of a quick way I can figure out which line in the function is causing the slowdown? Ideally something that will tell me how long each function call in the function took. That may help debug further. 

I somewhat doubt that SQLite is so slow on Windows. Likely it's the Emacs package that interfaces with SQL that is doing things in a way that are suboptimal on Windows (similar to magit's Windows issue).

**Comment by jethrokuan** [comment] 2020-08-28 05:38
You can use Emacs `M-x profiler-start` to track how long each function call takes, but I think it may lead to misleading results.

The only substantial change made to DB building recently was the shift from `org-element-parse-buffer` to a regexp-based solution. This has empirically lead to faster builds on Linux (CI, and my machine).

One thing I noticed was that shifting to a regexp-based method for link extraction results in slower builds, and had reverted that change.

I see little reason why the regexp based methods should be so slow on Windows, re-search is used in many packages all over Emacs.

**Comment by nobiot** [comment] 2020-08-28 08:44
> @nobiot can you comment here? Are things working for you?

i’m on vacation away from my PC. will be happy to once i’m back; it will be in September...

**Comment by aaronbieber** [comment] 2020-08-31 23:46
I am also experiencing this problem with:

> - Emacs: GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)
>  of 2018-05-30
> - Framework: N/A
> - Org: Org mode version 9.3.7 (9.3.7-24-g7b657c-elpa @ c:/Users/Aaron/dotfiles/configs/emacs.d/elpa/org-20200831/)
> - Org-roam: 1.2.1

On:

> Microsoft Windows 10 Pro 10.0.18362 Build 18362

When I call `org-roam-db-build-cache`, Emacs hangs. I can open Task Manager and find my Emacs process then expand the process tree to find two SQLite processes. If I end both of those tasks, Emacs will eventually come back to life, throwing a file error: `(file-error "Writing to process" "Invalid argument" #<process emacsql-sqlite3>)`, which makes sense because I pulled sqlite3 out from under it and its connection handle is now invalid.

The debugger stack trace for that error indicates that it was in the middle of trying to `INSERT INTO links`, but I'm not sure if that helps anyone get further with this.

This is quite frustrating because Roam worked very well for the last couple months, and I didn't even encounter any of the update slowness described by others here (though Windows definitely handles many small files less efficiently than macOS or Linux generally).

I have both this Windows 10 Pro machine and a MacBook Pro, so if there is anything I could do to help suss this out please let me know.

**Comment by j-steinbach** [comment] 2020-09-01 12:07
If anyone is desperate for the org-roam functionality on Windows and looking for a "workaround" until this gets fixed, I recommend WSL -  the experience is almost as good as on native windows (I use WSL1). It took a bit to set-up, but everything works perfectly for me ([guide](https://github.com/hubisan/emacs-wsl)). Bonus: I could also finally install pdf-tools without problems.

**Comment by aaronbieber** [comment] 2020-09-05 10:32
I can confirm that rolling back to the latest release (v1.2.1) *is working* in Windows 10 Pro.

I deleted all `org-roam*` directories from my elpa install location and extracted the release zip and added it to my `load-path` manually, then restored the `(use-package ...` stanza that I had before and everything has returned to normal.

This proves, at least for my particular configuration, that the hanging issue isn't related to SQLite version, though I also ran some `emacsql` commands from the scratch buffer (creating a temporary SQLite file) to ensure that all the SQL mechanics were working.

**Comment by Whil-** [comment] 2020-09-06 08:16
Another datapoint here: (with org-roam on master, e3ff546)
```
(org-roam) files: Δ32, headlines: Δ26, links: Δ23, tags: Δ0, titles: Δ32, refs: Δ0, deleted: Δ0
Elapsed time: 8418.572164s (13.399037s in 247 GCs)
```

The files are quite big though, and not org-roam-esque. So lots of headings with ID's per file.

Trying out v1.2.1 give the following result:
```
(org-roam) files: Δ32, headlines: Δ26, links: Δ23, tags: Δ0, titles: Δ32, refs: Δ0, deleted: Δ0
Elapsed time: 42.587812s (17.183649s in 263 GCs)
```

So thanks @aaronbieber, for suggesting to roll back to that release!

**Comment by aaronbieber** [comment] 2020-09-06 11:13
@Whil- credit to the original reporter @ahristow for the rollback suggestion. I strongly urge maintainers to keep v1.2.1 as the current stable release until we figure this out, it is a crippling issue for Windows users.

I couldn't find documentation on that profiler output so I am guessing, but I believe typically the first elapsed time is "wall clock" time and the parenthesized time is "CPU time." What's interesting about your results is that there are very similar CPU times. That indicates that the difference (which is huge, if I'm reading it right), is almost completely waiting.

That makes sense, if we are waiting for either Windows filesystem IO or SQLite. In my trivial local experiments, SQLite responded quickly, so I'm skeptical that SQLite is the problem. It also makes sense that Windows filesystem IO should be the problem since we do not observe this behavior on other platforms.

Consequently, I wonder if some change was made between release v1.2.1 and current master that dramatically increased the number of disk operations (possibly by accident).

**Comment by sbenfold** [comment] 2020-09-06 16:45
Doing a bisect, it looks like https://github.com/org-roam/org-roam/commit/0318983cac2ae8e75eec37f234aac3e5b8d15e53 caused the hang.

**Comment by jethrokuan** [comment] 2020-09-07 02:54
> I strongly urge maintainers to keep v1.2.1 as the current stable release until we figure this out, it is a crippling issue for Windows users.

I don't intend to cut a release with until these reports are cleared.

https://github.com/org-roam/org-roam/commit/0318983cac2ae8e75eec37f234aac3e5b8d15e53 looks like a relatively benign change.

Can someone who is facing this issue provide a small set of files (preferably 1) that can demonstrate long build times (maybe 10s or more)?

**Comment by nobiot** [comment] 2020-09-09 11:48
I updated my Org-roam via MELPA to `org-roam-20200904.1305`, and did a quick test on my Windows 10 machine. I didn't experience the same performance issue. 

I will try to do a bit more thorough testing on my end. The notes I used for my quick test did not have [[fuzzy link]] or URL links of type "https" as @j-steinbach shows in the spreadsheet example above. So they may be the factor(s).

If I could also have sample files with the long-build time issues, I would be happy to try to reproduce the issue on my Windows PC, too.

**Comment by nobiot** [comment] 2020-09-10 21:32
@jethrokuan, I think I have managed to repro the performance issue on my Windows machine. 
As far as I have seen, the `save-buffer` finishes in fraction of a second. Then after 2-3 seconds of idle time, database update kicks in (I assume this is your design with `org-roam--file-update-timer`). 

When the file contains https (probably http too) link, Emacs hands for about 40-60 seconds (this is just my feel; don't know how to measure a background process with Emacs).  

I don't observe this with a note with only fuzzy links (`[[title of the note]]`, when `org-roam-auto-replace-fuzzy-links` is set to `nil`).

See my bench mark for database build, comparing 5 notes with https links, and the same notes with just the links removed.
100 seconds vs 3 seconds (!).

---

 [2020-09-10 Thu] Tested with vanilla Emacs and org-roam-20200907.214 (MELPA)
The files for both cases and my init.el shared here:
https://github.com/nobiot/org-roam-performance-test-v1.2.1-Windows

---

## 5 org files with https links

#+begin_src emacs-lisp
;;(org-roam-db--close-all)
;; delete the db file manually
(benchmark 1 '(org-roam-db-build-cache))
#+end_src

RESULTS:
: Elapsed time: 100.635170s

## 5 org files with https links manually removed

#+begin_src emacs-lisp
;;(org-roam-db--close-all)
;; delete the db file manually
(benchmark 1 '(org-roam-db-build-cache))
#+end_src

RESULTS:
: Elapsed time: 3.484243s
Second result to make sure I deleted the db file correctly...
: Elapsed time: 3.598303s (0.042483s in 1 GCs)

**Comment by jethrokuan** [comment] 2020-09-11 06:43
Thanks for the files @nobiot . It seems like you have narrowed down the cause of slowdown to link extraction (https links in particular seem to cause this issue).

I have used the set of files you have provided on my Linux machine, and updates remain instant. So this issue really seems to be Windows-specific. Can you help me confirm that link extraction is an issue by running:

`(benchmark 1 (org-roam--extract-links))` within the file that has `https` links?

**Comment by sbenfold** [comment] 2020-09-11 09:59
Timings on Windows 10 using a file with the following:
- 35 lines
- 4 file links
- 17 https links
Unfortunately I used a private file that I can't share.

`(version)`
GNU Emacs 26.2 (build 1, x86_64-w64-mingw32) of 2019-04-13

9753ee451f2c16c3af74edf4748cbcac38f04830 (org-roam-20200810.838)
| `(benchmark 1 '(org-roam--extract-links))` | `(benchmark 3 '(org-roam--extract-links))` | `(benchmark 10 '(org-roam--extract-links))` |
|---|---|---|
| 0.061580s |0.185802s|0.723128s (0.104389s in 1 GCs)|
| 0.062609s |0.187897s|0.677855s|
| 0.063074s |0.192519s|0.718688s|
| 0.062847s |||
| 0.062981s |||
| 0.070062s |||

0318983cac2ae8e75eec37f234aac3e5b8d15e53 (org-roam-20200810.859)
| `(benchmark 1 '(org-roam--extract-links))` | `(benchmark 3 '(org-roam--extract-links))` | `(benchmark 10 '(org-roam--extract-links))` |
|---|---|---|
| 33.645940s | 33.980995s | 0.769658s |
| 0.075050s | 34.098351s | 34.554702s |
| 33.864047s | | 34.500064s |
| 0.075828s |||
| 33.691436s |||
| 0.074124s |||

This confirms my suspicion that https://github.com/org-roam/org-roam/commit/0318983cac2ae8e75eec37f234aac3e5b8d15e53 introduced the regression. I don't know why sometimes the times are <1s. I wonder if there's some kind of caching happening.

**Comment by nobiot** [comment] 2020-09-11 12:07
Similar results.

In File2 of my samples, added the following line, and evaluate the sexp.
During the evaluation, Emacs freezes, and does not accept user inputs.
```
(benchmark 1 '(org-roam--extract-links))
```
"Elapsed time: 66.141189s"
"Elapsed time: 47.264526s"
"Elapsed time: 59.210664s"
"Elapsed time: 60.043152s"
org-roam-20200907.214 (MELPA)

FYI, so as not to kill the momentum: I'll be again away from my PC for the weekend...
Will be back next week.

**Comment by nobiot** [comment] 2020-09-11 16:51
I'm on a train with no PC, but reading code diff for 0318983 following @sbenfold; I could not help it 😅 

A totally wild guess and would have done it myself with my PC...

![Uploading 92951109...]

Here the condition check whether or not the link (or part of it) is "file" or not appears to have been removed. `f-relative-p` in the end calls `file-name-absolute-p`, which expects `path` as an argument -- perhaps if a URL is passed here, Windows somehow tries to resolve it, and spend an enormous amount of time?

Apologies if this is to be a total waste of time for someone kind enough to try this on Windows (I would have done it myself. I could not help but pass the button to someone; could not wait until I come back after the weekend). If no one can try it, of course I'll do it myself later 😃

**Comment by ahristow** [comment] 2020-09-14 09:36
I tested @nobiot's "totally wild guess" on my Windows machine. Since I have the v1.2.1 release of org-roam installed, I worked in the opposite direction and essentially tried to break my install by changing the appropriate lines (1210-1211, in this case). For better or for worse, nothing changes -- the database builds successfully, and in about the same amount of time as before.

I went on vacation not long after reporting this, but I'm back now and have both Windows and Linux boxes at my disposal. If I can assist in any way I'd be happy to try, though I should caution that I'm pretty inept when it comes to Elisp debugging and might require some hand-holding.

**Comment by jethrokuan** [comment] 2020-09-14 11:29
> Since I have the v1.2.1 release of org-roam installed, I worked in the opposite direction and essentially tried to break my install by changing the appropriate lines (1210-1211, in this case).

I don't think changing it like this would be helpful. In your installation, only `file:...` links will be iterated over in that function, so there would be no observable difference. To truly test if that is the issue, you would need to make @nobiot's change on the master branch.

> If I can assist in any way I'd be happy to try, though I should caution that I'm pretty inept when it comes to Elisp debugging and might require some hand-holding.

Sure, I'm happy to guide you along. Unfortunately I don't have a Windows machine accessible to me, so I can't work on Windows-specific issues. I think I found the possible issue, could someone test if this branch works for them?

https://github.com/org-roam/org-roam/pull/1103

**Comment by ahristow** [comment] 2020-09-14 15:46
> To truly test if that is the issue, you would need to make @nobiot's change on the master branch.

Yeah, that makes sense -- I might not be much for debugging Elisp, but I have enough experience with other languages that I should have realized that myself. I guess my brain is not quite back from vacation....

In any case, I went back and tried it, starting from the same commit @nobiot used. It didn't work -- I let it run a good 15 minutes before I gave up and killed Emacs.

> I think I found the possible issue, could someone test if this branch works for them?

I tested #1103. Unfortunately, the issue persists.

**Comment by nobiot** [comment] 2020-09-14 20:21
@jethrokuan , @ahristow , 
Yes, sorry, I was barking at the wrong tree. I tried #1103 with the same results as @ahristow .

But I think I found the the following three functions through `edebug`.
They are all called somewhere in function `org-roam--extract-links`.

The benchmarks were done with #1103 still implemented.

---
 ### Observation

If you benchmark the same function repeatedly multiple times, the duration is shorter on 2nd and 3rd runs.

If you execute the functions sequentially (1, 2, and then 3, and back to 1, 2, and 3), each function seems to last the longest time.

---

### Function 1. `file-attributes` inside `org-roam--expand-links`

```
#+begin_src emacs-lisp

(setq link "//www.newyorker.com/magazine/2018/03/19/reddit-and-the-struggle-to-detoxify-the-internet")

(benchmark 1 '(file-attributes link))
#+end_src
```
1st: Elapsed time: 22.716321s
2nd: Elapsed time: 0.007521s
3rd: Elapsed time: 0.004395s
`(f-relative-p link)` (my initial target) follows this, but it seems to be consistently around 0.000002s

### Function 2. expand-file-name

```
#+begin_src emacs-lisp
(setq path "//www.amazon.com/Andrew-Marantz/e/B07Z35ZG6B/ref=dp_byline_cont_book_1") 
(setq dir (list "c:/Users/nobiot/org-roam/"))
(benchmark 1 '(file-truename (expand-file-name path dir)))
#+end_src
```
1st: Elapsed time: 27.117486s
2nd: Elapsed time: 5.637003s
3rd: Elapsed time: 5.160000s

## Function 3. f-exists?

```
#+begin_src emacs-lisp
(benchmark 1 '(f-exists? "//www.amazon.com/Andrew-Marantz/e/B07Z35ZG6B/ref=dp_byline_cont_book_1"))
#+end_src
```
1st: Elapsed time: 23.363491s
2nd: Elapsed time: 1.989159s
3rd: Elapsed time: 1.897378s

**Comment by nobiot** [comment] 2020-09-14 20:23
If possible, it would be great if the code can be changed to avoid calling these functions if the "link" is a URL...

**Comment by nobiot** [comment] 2020-09-14 22:46
One more thing...

We may be looking at two different set of issues, though I need to test my suspicion a bit more thoroughly.

#1103 might have improved the speed of `save-buffer`. I was too focused on db build, and was not paying sufficient attention to it.

Debugging (`edebug`) session for `org-roam--extract-links` was not triggered on saving the buffer if I remember correctly.

@jethrokuan , does this make sense? I mean:
1. #1103 might have improved `save-buffer` without affecting db build
2. `org-roam--extract-links` is used within db build, but not in save buffer
3. We are observing two separate sets of performance issues on Windows (1 & 2)

**Comment by jethrokuan** [comment] 2020-09-15 05:13
Wow, the benchmark results for the file-related functions are both strange and upsetting. I guess we've found the cause of the issue, but it seems like the fix should be somewhere upstream in Emacs instead. I don't see why finding attributes on a file that does not exist should take so long.

> If possible, it would be great if the code can be changed to avoid calling these functions if the "link" is a URL...

I'm actually calling the function to *figure out if* the link is a URL so...

> org-roam--extract-links was not triggered on saving the buffer if I remember correctly.

It is triggered later on in the file update queue, compared to the previous stable windows version.

**Comment by Whil-** [comment] 2020-09-15 09:43
Interesting find nobiot!

From org-roam's perspective, maybe it's possible to determine if a link is to a file by the link type? I.e. we're now discussing _https:_ links, and those are per definition never files and always URL's.

**Comment by jethrokuan** [comment] 2020-09-15 09:54
> From org-roam's perspective, maybe it's possible to determine if a link is to a file by the link type? I.e. we're now discussing https: links, and those are per definition never files and always URL's.

Yes and no. We can explicitly filter out for web links (e.g. http, https), but then we won't be able to support arbitrary Org links that other packages may add, e.g. `youtube:...` or `org-brain:...`.

**Comment by nobiot** [comment] 2020-09-15 11:06
> I'm actually calling the function  to figure out if the link is a URL so...

This is only about `file-attributes`, right? The other two are rather used as existence check? 

It looks to me that `file-attributes` is used in this [part](https://github.com/org-roam/org-roam/pull/1103/files#diff-0c901a6495bf5e72da2d3526eb3f6483R535-R536) in the fix/windows branch (the master branch is different).
```
        (when (and (file-attributes link)
                   (f-relative-p link))
```
Could you not swap the sequence of the expressions? `f-relative-p` first, `file-attributes` second in this `and` condition check?
I could be mistaken, but I would have thought Elisp would skip the second function if the first one returns `nil` -- it's an `and` check; both needs to be `t`. 

My finding is that `f-relative-p` is quick.

I'll see if my thinking works later.

**Comment by nobiot** [comment] 2020-09-15 11:13
FYI.
C code [source ](https://git.savannah.gnu.org/cgit/emacs.git/tree/src/dired.c?h=emacs-27#n851) of `file-attributes` in Emacs 27.

I tried variable `w32-get-true-file-attributes` `nil` (default on my Doom), and "local" like the following:

- `(setq w32-get-true-file-attributes "local")`
- `(setq w32-get-true-file-attributes 'local)`

Like this:
```
(setq link "//www.newyorker.com/magazine/2018/03/19/reddit-and-the-struggle-to-detoxify-the-internet")
(setq w32-get-true-file-attributes "local")
(benchmark 1 '(file-attributes link))
```

Not sure if I set the variable correctly to "local" as the function expects, but no change in the performance...

**Comment by nobiot** [comment] 2020-09-15 19:08
Created a PR for you to peruse.

Two changes:

1. Swapped the sequence of (file-attributes link) and (f-relative-p) in `org-roam--expand-links` (addresses Function 1 in my benchmarks above)
2. Added small check if the "path" starts with "//" -- indicating that it's a URL (Function 2 & 3)

I believe these are minimal changes and I tried my best to keep the intent/semantics of the original code (hopefully).
I have not done regression testing to check if the change breaks anything (@jethrokuan , you may not like how the second change is implemented). 

Also, if there is other links (like youtoube:, org-brain:, etc., as Jethro suggests above), we should be able to introduce a new function in its place to implement more elaborate checks as they come.

See the performance improvement I have observed below (but of course, if I have broken the original intended function, then this is no improvement anyway).

---

With using [test files](https://github.com/nobiot/org-roam-performance-test-v1.2.1-Windows) of five (5) `.org` notes with `https` URL links, the following performance improvement is observed:

---

### Steps / code executed for benchmark

```
#+begin_src emacs-lisp
;;(org-roam-db--close-all)
;; delete the db file manually
(benchmark 1 '(org-roam-db-build-cache))
#+end_src
```

### Results
[2020-09-15 Tue]
Before change
Elapsed time: 123.473523s (0.506992s in 12 GCs)

After change
1st: Elapsed time: 0.253582s
2nd: Elapsed time: 0.240944s
3rd: Elapsed time: 0.568807s (0.043532s in 1 GCs)

**Comment by TimQuelch** [comment] 2020-09-16 00:26
@nobiot Very small tangent about your benchmark procedure and you probably already know this: 

> ;; delete the db file manually

`(org-roam-db-build-cache t)` will automatically delete the db before building. This might speed up your workflow a little bit because you don't have to delete it manually

**Comment by nobiot** [comment] 2020-09-16 17:14
@TimQuelch , thanks for that 👍 
For Windows, I needed to close the DB connection before db-build to force rebuild, and it works. 
```
#+begin_src emacs-lisp
(org-roam-db--close-all) ;you need to close db conn for Windows to avoid "Permission deined"
(benchmark 1 '(org-roam-db-build-cache t)) ;forces re-build
#+end_src
```
Updated the PR based on @jethrokuan 's review.
Benchmark results look positive :)

I am still somewhat unconvinced as to why it should be now faster than the previous benchmark results before the change for files without URL links... But this is the result...

---

Before change (checked by going back to commit 7044900
: Elapsed time: 192.933603s (0.380618s in 12 GCs)

After change
1st: Elapsed time: 0.757395s (0.043884s in 1 GCs)
2nd: Elapsed time: 0.610628s (0.041096s in 1 GCs)
3rd: Elapsed time: 0.497729s (0.038485s in 1 GCs)

**Comment by nobiot** [comment] 2020-09-16 17:20
FYI.

As a follow up, I did benchmark the same set of 5 org files with no URL links.

Every run outputs the 5 files delta, so DB is cleared and forced to be rebuilt correctly. 
The performance gain from before the change is indeed very good.
```
(org-roam) files: Δ5, headlines: Δ0, links: Δ5, tags: Δ0, titles: Δ5, refs: Δ0, deleted: Δ0
```

1st: Elapsed time: 0.499613s (0.035227s in 1 GCs)
2nd: Elapsed time: 0.483879s (0.036623s in 1 GCs)
3rd: Elapsed time: 0.486957s (0.035256s in 1 GCs)
The previous benchmark result was 3.484243s -- 1/100 (!)

**Comment by ahristow** [comment] 2020-09-17 08:16
I just tested commit https://github.com/org-roam/org-roam/commit/6c89eb82af94f76c61e5a68a16c140b9ca98e559 from the master branch on my Windows machine. Building a new db from scratch took roughly 2.5 minutes for ~600 files containing a mix of link types. For me, at least, the problem seems solved.

**Comment by pcrama** [comment] 2020-09-18 21:52
Please see my [comment](https://github.com/org-roam/org-roam/pull/1103/commits/e1216e4ffa47db274bbe7d71b3e447b8d8062111#r491206682):

Suggestion: use something like `(and (string-match-p ffap-url-regexp type) (org-roam--is-url-p path))`

On windows, `\\network\share$\path\file.org` is a valid file name and emacs will replace `/` with `\` so that 
- https://google.com/ gets split into type="https" and path="//google.com/"
- type does not match any pattern and `(file-remote-p path)` returns nil (I just tried and `(file-remote-p (concat type ":" path))` is nil, too, so no help there)
- so the code ends up trying `(file-truename path)` and on my Windows systems (8.1 & 10), `(file-truename "//google.com/")` will take a very long time (probably a network timeout) because emacs tries to access "google.com" as if it was a file server

On Linux, the problem is (less ?) visible, because `//google.com/` is interpreted as `/google.com/` and unless you happen to have a `google.com` symbolic link in your root folder to somewhere else, nothing bad happens... but if there was such a symbolic link, a different path would get registered, I guess.

**Comment by nobiot** [comment] 2020-09-20 16:46
> On windows, \\network\share$\path\file.org is a valid file name and emacs will replace / with \ so that
> ...
> the code ends up trying (file-truename path) and on my Windows systems (8.1 & 10), (file-truename "//google.com/") will take a very long time (probably a network timeout) 

This makes sense...

I can't think of a better way to handle this to be compatible with both Linux (+MacOS) and Windows.

Intuitively, the code below would be OK for Windows (perhaps `org-roam--url-p` should be re-named to `org-roam--w32-file-on-network-drive-p`). A "remote file (Linux/MacOS)" is a "file on a network drive (Windows)", correct?

I feel that I am probably thinking about this too crudely, and seem to be unable to grasp some important points here

```
                          (_ (if (or (file-remote-p path)
                                     (org-roam--url-p path))
                                 (list path)
```

**Comment by pcrama** [comment] 2020-09-20 20:24
`file-remote-p` checks for TRAMP syntax file names (e.g. `(file-remote-p "/ssh:user@host:p")` returns `"/ssh:user@host:p"` (i.e. not NIL))

> I can't think of a better way to handle this to be compatible with both Linux (+MacOS) and Windows.

And it's made more difficult by the fact that the same zettelkasten could very well written and accessed on several systems running different OSes.

I believe there are different kinds of values that `type` + `path` can take:
- "file" + "//a/b/c/d": it is likely that the link was made on a Windows machine to a network share and whether we are on a UNIX-like system or Windows, it doesn't matter: we should not try to `(file-truename path)`: on Windows, it would try to access a server and would lead to slowness, on Linux/MacOS, the double `/` would be seen as just `/` and interpreting the likely network share's host name ("a" in my example) as directory name in the root directory is meaningless.
- "file" + "c:/d/e": the link was made on a Windows machine, running `file-truename` there is safe (even if it was removable media and it was ejected in the meantime, from a cursory test on my Windows 8.1 machine).  Doing a `file-truename` on a Linux/MacOS on such a file is hard to predict (i.e. it could return a wrong value for an artificial scenario involving the right current working directory and a symbolic link with the right name (is `:` allowed as character in a Linux/MacOS filename?) )but should at least not be slow.
- "https" + "//c.de/f/g": given the value of `type`, we should not even bother looking at `path`.

So I believe the correct fix is to add network protocols ("http", "https", "gopher", "ftp", ... I don't know if the list is well-defined) to the `"fuzzy"` pattern *and* to rename `org-roam--url-p` to `org-roam--likely-w32-network-share-path-p`, but the two are necessary.

**Comment by nobiot** [comment] 2020-09-21 10:14
It's a great analysis.

@jethrokuan is working to change the current fuzzy link implementation to one that uses type "roam:" if I understand it correctly. I suppose we should park our discussion here until Jethro finishes that changeover. 

@pcrama's analysis will be useful when we come back to it.

**Comment by jethrokuan** [comment] 2020-09-22 06:05
#1109 removed file-truename everywhere, so there should be no resolution of paths at all now. 

```
(expand-file-name "//google.com" default-directory) => //google.com
(expand-file-name "c:/d/e" default-directory) => "/home/jethro/c:/d/e"
(expand-file-name "//a/bc/d" default-directory) => "//a/bc/d"
```
It appears that the windows drives are still an issue, but i'm not sure if it's because `expand-file-name` behaves differently on a Linux machine.

**Comment by pcrama** [comment] 2020-09-22 06:39
From `expand-file-name` doc-string:
> Multiple consecutive slashes are collapsed into a single slash, except at the beginning of the file name when they are significant (e.g., UNC file names on MS-Windows.)

So I think that MS-Windows UNC paths will now be handled correctly.  At least, `expand-file-name` will not access the network, which will remove the issue of trying to connect to a networked drive that may or may be not available.

Your example `(expand-file-name "//google.com" default-directory)` should not happen if part of my suggestion is applied: for such a link, `type` would be `"https"` so it should not even go to the file handling case.  I would argue to treat `"file"` links differently from e.g. `"https"` links even if the usage of `expand-file-name` on a URL has no bad side-effects, I think it makes it clear which case is for files and which case is for other links.

Your other example `(expand-file-name "c:/d/e" default-directory)` is an interesting question: I sync my zettelkasten (only the org files, not the org-roam.db) between different PCs (Windows + Linux where my `org-roam-directory` is not even the same everywhere), so I do not get bitten by it (they each have their own org-roam.db).  But the consequence of not syncing org-roam.db is that if it ever were to become more than a cache (e.g. store metadata like frequency of access that conceivably should be shared across my replicas), I would lose functionality.  Yet, with absolute paths stored in the org-roam.db (instead of relative paths rooted in the same directory) I can't sync the org-roam.db (not a complaint, just a note about a bridge I will cross when/if needed).

**Comment by jethrokuan** [comment] 2020-09-30 05:35
Closing this since `file-truename` calls are now mostly gone, and the original issue shouldn't exist anymore.

**Closed by jethrokuan** 2020-09-30 05:35 UTC
Labels: windows
