### ISSUE TITLE
v2: Include indirectly linked nodes in node-local graphs

### ISSUE THREAD

**Issue by Wetlize** [org-roam/org-roam#1561] opened 2021-06-24 23:59 UTC
### Description
At the current moment, node-local graphs only include nodes that are linked directly through ID based links (be it custom links or `id:` based one). Nodes that are linked indirectly, e.g. by referencing the needed node through assigned ref or linked through shared forward links are not accounted by the local graph.

#### Steps to Reproduce
1. Create the next org-roam nodes (use a separate `org-roam-directory` for a better visualization):

```org
* Foo
:PROPERTIES:
:ID: foo
:ROAM_REFS: https://github.com/hlissner/doom-emacs
:END:
A paragraph that forward links to [[https://google.com][Google]] and [[https://github.com/org-roam/org-roam][Org-roam repo]].

* Bar
:PROPERTIES:
:ID: bar
:END:
A paragraph that forward links to [[https://google.com][Google]] and [[https://github.com/org-roam/org-roam][Org-roam repo]].

* Foobar
:PROPERTIES:
:ID: foobar
:END:
A paragraph that links to [[https://github.com/hlissner/doom-emacs][Foo]] node through ref link (not =id=!)

* Foobaaz
:PROPERTIES:
:ID: foobaaz
:END:
A paragraph that links with [[id:foo][Foo]] node directly through =id= link.

* Isolated node
:PROPERTIES:
:ID: isolated
:END:
This node shouldn't be included in node-local graphs for other nodes. It doesn't really serve any meaningful purpose, other than to differentiate itself more clearly from a node-local graph.

```

2. Build a global graph using `org-roam-graph` command to check how things will link with each other.
3. Build a node-local graph for `Foo` node, using `org-roam-graph` command.
4. Compare how things are linked in `org-roam-mode` for `Foo` node with the corresponding image of the local graph.

#### Expected Results
1. I would expect that in the node-local graph it would at least include nodes that link with `Foo` through it ref link, in our case specifically it should be `Foobar` node.
2. Since v2 now also renders forward links as separate nodes, it probably should also render nodes that connect to these links in the node-local graph too, in our case specifically it should be `Bar` node.

#### Actual Results
1. `Foobar` (node that links through ref) never appears as vertex in the node-local graph for `Foo` node.
    - it does, however, appear correctly as a ref based backlink in `org-roam-mode`
    - in the global graph, it doesn't link directly with `Foo` node, but instead links to a forward link to `https://github.com/hlissner/doom-emacs` vertex.
2. `Bar` node (node that uses the same forward links as `Foobar`) never appears as vertex in the node-local graph for `Foo` node.
    - forward links as `org-roam-mode` section is not implemented, so it shouldn't appear there, as expected.
    - in the global graph, it does link with the same forward links as `Foo` points to.

### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
of 2021-05-01
- Framework: Doom
- Org: Org mode version 9.5 (nil @ /home/user/.emacs.d/.local/straight/build-28.0.50/org-mode/)
- Org-roam: 2.0.0
- Org-roam commit: a5e9abe811406ff9650615aa4fab5884ad65326d

**Comment by Wetlize** [comment] 2021-06-25 00:03
As a refence, here's an image of the global graph:

![global_graph](https://user-images.githubusercontent.com/17055067/123348005-d78fc680-d561-11eb-9acc-baa73f7ad411.png)

And `Foo` local graph:

![local_graph](https://user-images.githubusercontent.com/17055067/123348113-e1192e80-d561-11eb-8edc-514684b583ed.png)

**Comment by Wetlize** [comment] 2021-06-25 00:22
I also think that it's fine to keep refs as forward-link based vertices, but it probably would be better to make them share an edge with a node that assign them as `ROAM_REFS` and color such node with a distinguishable color, Like this:

![global_graph_2](https://user-images.githubusercontent.com/17055067/123350855-86350680-d564-11eb-9eac-3149353f524a.png)

where red colored edge indicates ref's origin.

**Comment by Wetlize** [comment] 2021-06-25 00:26
So the final `Foo` local graph would look like this:

![local_graph_2](https://user-images.githubusercontent.com/17055067/123351122-2d19a280-d565-11eb-9ae8-357c6857c77d.png)

**Comment by Wetlize** [comment] 2021-07-01 16:34
@jethrokuan With 55008e3707c4960afbc6e2c0fcd6e72a1e60fc0a forward links are now displayed on the local graph just how expected, so this part is fixed. However, the node-local graph still doesn't includes nodes that link through `:ROAM_REFS:`.

**Comment by aruscher** [comment] 2021-07-26 22:32
@jethrokuan What's your opinion on this? Do agree with the posts by @Wetlize ? If you agree, I would start to work on a fix.

**Comment by jethrokuan** [comment] 2021-07-27 03:59
Yes, You can bulk fetch all items from the `refs` table and add them as edges to the graph, with a different style.

**Comment by jethrokuan** [comment] 2021-07-30 19:46
Closing this issue as a duplicate of #1677 , where 1677 is more specific (some parts of this issue have already been fixed)

**Closed by jethrokuan** 2021-07-30 19:46 UTC
Labels: v2
