### ISSUE TITLE
Trailing slash in "org-roam-directory" breaks "org-roam-db-build-cache"

### ISSUE THREAD

**Issue by minosniu** [org-roam/org-roam#732] opened 2020-05-30 02:24 UTC
### Description
I have my org-roam-notes synced between two Macs. Both Macs were under almost exactly the same configuration, but one kept failing at  "org-roam-db-build-cache".

After careful comparison, the only difference was that the failing Mac had "org-roam-directory" set to "~/local-roam-notes/" with a trailing slash.

After removing the trailing slash, the error went away. Now I'm able to see connected graphs, add new notes, and insert links identically between 2 synced machines.

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.0.0, NS appkit-1894.10 Version 10.15.1 (Build 19B88))
 of 2019-11-17
- Framework: Spacemacs
- Org: Org mode version 9.3.6 (9.3.6-17-g389288-elpaplus @ /Users/minosniu/.emacs.d/elpa/develop/org-plus-contrib-20200224/)
- Org-roam: 1.1.

**Comment by progfolio** [comment] 2020-05-30 02:38
Duplicate of #695

**Comment by jethrokuan** [comment] 2020-05-30 12:33
This should be fixed by #735, do reopen if it's still an issue.

**Closed by jethrokuan** 2020-05-30 12:33 UTC
Labels: bug, tag: duplicate
