### ISSUE TITLE
Need maintainable Windows 10 install

### ISSUE THREAD

**Issue by notuntoward** [org-roam/org-roam#682] opened 2020-05-21 23:20 UTC
I'd like to try out `org-roam` but the [Windows 10 install instructions](https://org-roam.readthedocs.io/en/master/installation/) are formidable, and will have to be repeated every time I update the org-roam package.  Can the Windows 10 install please be made simpler?

The problem is with `emacsql-sqlite3`:  I already have the two most popular unix tool sets installed on my machine (`msys2 `and `choco`) but both have only have options to install `sqlite3`.  By default, org-roam expects plain `sqlite`, meaning that I'll need to edit the `org-roam` source code in three places and then compile; every time the `org-roam` package is updated, I'll need to redo these steps.

Is there a way that `org-roam` can detect which version of `sqlite` is installed and  then just do the right thing?

**Comment by visuelledata** [comment] 2020-05-22 03:54
These install instructions aren't even feasible for people who want to have an easily replicable setup. Any idea what the latest version of org-roam that is Windows-compatible is?

**Comment by jethrokuan** [comment] 2020-05-22 04:02
> Is there a way that org-roam can detect which version of sqlite is installed and then just do the right thing?

That's not something org-roam can control. That just means `emacsql-sqlite` is not particularly platform-agnostic, and doesn't work out-of-the-box. By default, it expects that you have the necessary tools to compile the custom sqlite executable. You can try pointing it to the path to your local sqlite installation: https://github.com/skeeto/emacsql/blob/master/emacsql-sqlite.el#L30

```
(setq emacsql-sqlite-executable-path "...")
```

That said I'm happy to accept any reasonable changes to get better out-of-the-box windows support. I have no windows machines at all, and cannot test and work on this scenario.

**Comment by jueqingsizhe66** [comment] 2020-05-22 14:11
Windows10  platform with newest version of org-roam
（org-roam works well in the older version, now just have no idea to fix it）  
The bugs just right below by executing `org-roam-insert `

```
Debugger entered--Lisp error: (emacsql-error "no such table: tags")
  signal(emacsql-error ("no such table: tags"))
  #f(compiled-function (_ code message) "Get condition for MESSAGE provided from SQLite." #<bytecode 0x5082cd9>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> 1 "no such table: tags")
  apply(#f(compiled-function (_ code message) "Get condition for MESSAGE provided from SQLite." #<bytecode 0x5082cd9>) #<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> (1 "no such table: tags"))
  emacsql-handle(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> 1 "no such table: tags")
  #f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x23677fd>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8>)
  apply(#f(compiled-function (connection) "Parse well-formed output into an s-expression." #<bytecode 0x23677fd>) #<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> nil)
  emacsql-parse(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8>)
  #f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x4d876a9>)(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> [:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)])
  apply(#f(compiled-function (connection sql &rest args) "Send SQL s-expression to CONNECTION and return the results." #<bytecode 0x4d876a9>) #<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> [:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)])
  emacsql(#<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> [:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)])
  apply(emacsql #<emacsql-sqlite-connection emacsql-sqlite-connection-51037d8> [:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)] nil)
  org-roam-db-query([:select [titles:file titles:titles tags:tags files:meta] :from titles :left :join tags :on (= titles:file tags:file) :left :join files :on (= titles:file files:file)])
  org-roam--get-title-path-completions()
  org-roam-insert(nil)
  funcall-interactively(org-roam-insert nil)
  #<subr call-interactively>(org-roam-insert record nil)
  apply(#<subr call-interactively> org-roam-insert (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> org-roam-insert record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (org-roam-insert record nil))
  call-interactively(org-roam-insert record nil)
  command-execute(org-roam-insert record)
  counsel-M-x-action("org-roam-insert")

```

**Comment by jueqingsizhe66** [comment] 2020-05-22 14:17
Org roam is updating from verion 3 to version 5

`(defconst org-roam-db--version 5)`

**Comment by progfolio** [comment] 2020-05-22 14:33
@jueqingsizhe66 please open a separate issue and paste the full output of `M-x org-roam-diagnostics` in the template.

**Comment by notuntoward** [comment] 2020-05-22 23:46
The problem with only hardcoding the path is that `msys2` and `choco` don't have compatible binaries -- they provide an `sqlite3.exe` binary, and if I hardcode the path to it, as suggested, emacs startup hangs until it times out.  I don't know exactly why, but it must be because `sqlite3.exe` doesn't behave as expected.  

So I tried it the other way, and made the suggested source code modifications for `emacsql-sqlite3`.  Emacs no longer hangs on startup, but I get the following error message:

> org-roam-db-build-cache: Opening input file: Invalid argument, c:/Users/scott/OneDrive/scotto/File not found - "*.org.gpg"

In my .emacs, I have:

> (org-roam-directory "~/tmp/org-roam") 

and in `~/tmp/org-roam`, I see a single file named `org-roam.db`.  Also `M-x org-roam-find-directory` opens an emacs window in the `org-roam-directory`.

Do you have any advice?

**Comment by progfolio** [comment] 2020-05-23 00:22
Can you evaluate the following?:
```emacs-lisp
(let ((debug-on-error t)
      (org-roam-list-files-commands nil))
  (org-roam-db-build-cache t))
```
If you hit an error, you'll be popped to a debug window. Copy and paste the full text of that window here.

**Comment by notuntoward** [comment] 2020-05-23 01:00
Sure.  Here's the debug window content:

> Symbol's function definition is void: org-roam-db-build-cache
> 
> To ensure normal operation, you should investigate and remove the
> cause of the error in your initialization file.  Start Emacs with
> the ‘--debug-init’ option to view a complete error backtrace.

If I start again with the --debug-init flag, I see this:

> 
> Debugger entered--Lisp error: (void-function org-roam-db-build-cache)
>   (org-roam-db-build-cache t)
>   (let ((debug-on-error t) (org-roam-list-files-commands nil)) (org-roam-db-build-cache t))
>   eval-buffer(#<buffer  *load*> nil "c:/Users/scott/OneDrive/scotto/.emacs" nil t)  ; Reading at buffer position 97490
>   load-with-code-conversion("c:/Users/scott/OneDrive/scotto/.emacs" "c:/Users/scott/OneDrive/scotto/.emacs" t t)
>   load("~/.emacs" t t)
>   #f(compiled-function () #<bytecode 0x1000baab9>)()
>   command-line()
>   normal-top-level()

**Comment by progfolio** [comment] 2020-05-23 01:07
Can you please paste the relevant section of you init file where you configure org-roam?

**Comment by notuntoward** [comment] 2020-05-23 01:37
Here you go:

```
(use-package emacsql-sqlite3)

(use-package org-roam
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-directory "~/tmp/org-roam") ; for now...
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n j" . org-roam-jump-to-index)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))

```

**Comment by progfolio** [comment] 2020-05-23 01:55
Thank you.
Try replacing your configuration for those two packages with this (replacing the sqlite3 path with the appropriate value):
```emacs-lisp
(use-package emacsql-sqlite3
  :custom (emacsql-sqlite-executable-path "/path/to/sqlite3.exe"))

(use-package org-roam
  :custom
  (org-roam-directory "~/tmp/org-roam")
  (org-roam-list-files-commands nil)
  :config (org-roam-mode))
```
And launching with `--debug-init`.
If you get an error paste the backtrace here.

**Comment by notuntoward** [comment] 2020-05-23 02:38
Progress!  No error messages now, and I've made my first couple notes -- thanks for getting me started.

1. Just so  you know, my config came almost verbatim from [here](https://org-roam.readthedocs.io/en/master/installation/).  So maybe some edits are warranted, although I'm not sure what.
2. I don't understand why `org-roam` didn't find `sqlite3.exe` on my Windows `PATH`.  It's on it.
3. It seems that the code I modified, following these [Windows instructions](https://org-roam.readthedocs.io/en/master/installation/) could be made more configurable, something like:
```
if windows-nt, then 
   use sqlite3 
else 
  use "ordinary sqlite" 
```
Or is there something wrong about that from a design point of view?

**Comment by progfolio** [comment] 2020-05-23 03:10
Glad to see you're able to get it working. I agree we could and should make the Windows installation less of a hassle. Unfortunately, I am not a Windows user, either, which makes it harder to test. I'm sure we can get a VM going to experiment.

The error you were hitting before:
> org-roam-db-build-cache: Opening input file: Invalid argument, c:/Users/scott/OneDrive/scotto/File not found - "*.org.gpg"

Looks unrelated to the sqlite3 issue. It looks like it could be an issue with `org-roam-find-file-commands` which was recently added. A couple follow up questions if  you don't mind:

- Do you have executables for `find` or `rg` installed?
- If you change the value of `org-roam-list-files-commands`  to `'(find rg)` in your config, relaunch Emacs with `--debug-init` do you hit the error I quoted above?

**Comment by notuntoward** [comment] 2020-05-23 03:48
Hmm, good questions:  

* Yes, I have `rg` but the `find` that's first on my `PATH ` is [this find](url).  
* If I use `'(find rg)`, I get the error
* If I use `'(rg find)`, then `org-roam` just rips along

Here's the debug message for '(find rg)`:
```
Debugger entered--Lisp error: (file-error "Opening input file" "Invalid argument" "c:/Users/scott/File not found - \"*.org\"")
  insert-file-contents("File not found - \"*.org\"")
  org-roam-db-build-cache()
  org-roam-mode()
  (progn (org-roam-mode) t)
  (condition-case err (progn (org-roam-mode) t) ((debug error) (funcall use-package--warning53 :config err)))
  (if (not (require (quote org-roam) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote org-roam)) :error) (condition-case err (progn (org-roam-mode) t) ((debug error) (funcall use-package--warning53 :config err))))
  (progn (customize-set-variable (quote org-roam-directory) "~/tmp/org-roam" "Customized with use-package org-roam") (customize-set-variable (quote org-roam-list-files-commands) (quote (find rg)) "Customized with use-package org-roam") (if (not (require (quote org-roam) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote org-roam)) :error) (condition-case err (progn (org-roam-mode) t) ((debug error) (funcall use-package--warning53 :config err)))))
  (condition-case err (progn (customize-set-variable (quote org-roam-directory) "~/tmp/org-roam" "Customized with use-package org-roam") (customize-set-variable (quote org-roam-list-files-commands) (quote (find rg)) "Customized with use-package org-roam") (if (not (require (quote org-roam) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote org-roam)) :error) (condition-case err (progn (org-roam-mode) t) ((debug error) (funcall use-package--warning53 :config err))))) ((debug error) (funcall use-package--warning53 :catch err)))
  eval-buffer(#<buffer  *load*> nil "c:/Users/scott/OneDrive/scotto/.emacs" nil t)  ; Reading at buffer position 98487
  load-with-code-conversion("c:/Users/scott/OneDrive/scotto/.emacs" "c:/Users/scott/OneDrive/scotto/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x1000baab9>)()
  command-line()
  normal-top-level()
Debugger entered--Lisp error: (file-error "Opening input file" "Invalid argument" "c:/Users/scott/File not found - \"*.org\"")
  insert-file-contents("File not found - \"*.org\"")
  org-roam-db-build-cache()
  org-roam-mode()
  (progn (org-roam-mode) t)
  (condition-case err (progn (org-roam-mode) t) ((debug error) (funcall use-package--warning53 :config err)))
  (if (not (require (quote org-roam) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote org-roam)) :error) (condition-case err (progn (org-roam-mode) t) ((debug error) (funcall use-package--warning53 :config err))))
  (progn (customize-set-variable (quote org-roam-directory) "~/tmp/org-roam" "Customized with use-package org-roam") (customize-set-variable (quote org-roam-list-files-commands) (quote (find rg)) "Customized with use-package org-roam") (if (not (require (quote org-roam) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote org-roam)) :error) (condition-case err (progn (org-roam-mode) t) ((debug error) (funcall use-package--warning53 :config err)))))
  (condition-case err (progn (customize-set-variable (quote org-roam-directory) "~/tmp/org-roam" "Customized with use-package org-roam") (customize-set-variable (quote org-roam-list-files-commands) (quote (find rg)) "Customized with use-package org-roam") (if (not (require (quote org-roam) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote org-roam)) :error) (condition-case err (progn (org-roam-mode) t) ((debug error) (funcall use-package--warning53 :config err))))) ((debug error) (funcall use-package--warning53 :catch err)))
  eval-buffer(#<buffer  *load*> nil "c:/Users/scott/OneDrive/scotto/.emacs" nil t)  ; Reading at buffer position 98487
  load-with-code-conversion("c:/Users/scott/OneDrive/scotto/.emacs" "c:/Users/scott/OneDrive/scotto/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x1000baab9>)()
  command-line()
  normal-top-level()
```

**Comment by progfolio** [comment] 2020-05-23 03:55
Thank you! As I suspected this is a bug in the new file finding behavior that was recently added. I'll investigate and get it fixed.

**Comment by nobiot** [comment] 2020-05-24 14:39
I have been wrestling with the `org-roam-find-file-command` issues on my Windows 10 all day today.
Setting it back to the old way `(setq org-roam-list-files-commands '(elisp))` got me going for now.

My gentle suggestion is to make `elisp` its default value. 

I believe Windows users would find it harder to get through this error than Linux and macOS users. As far as I could see, it essentially breaks org-roam for Windows because `find` is not workable, and it's the first one the current default uses. 

I was going to open a new issue, but I'll put my quick report of my observation below.
Let me know if you would like a new issue open.

`find` on Windows lead to an error on my Windows 10 machine similar to @notuntoward reports above -- instead of`*.org`, mine is for `*.org.gpg`:

![image](https://user-images.githubusercontent.com/12507865/82756642-b9461d00-9ddb-11ea-905e-c56c5c9a896a.png)
**Figure 1.** Return message while debugging `org-roam--shell-command-files` for `rg`

![2020-05-24_15-15-34](https://user-images.githubusercontent.com/12507865/82756340-fa3d3200-9dd9-11ea-834f-4a2eae712eb7.png)
**Figure 2.** Actual `find` commend used on Windows 10 with parameters.

I suspect these parameters are designed for Unix-like systems, and that they are not compatible with Windows' `find` command -- I could not get `find` working with this parameter in `cmd` or `PowerShell`.


`rg` is installed via scoop in my case.
`shell-command-to-string` returns this strange path -- note the `\\` between my `org-roam-directory` and my file names (Figure 3 below, highlighted). I admit that I'm using my own plug-in to work with `md` files, but I suspect this part behaves in the same way.

![image](https://user-images.githubusercontent.com/12507865/82756431-95360c00-9dda-11ea-8629-bdf084efe21f.png)
**Figure 3.**  Debugging session with return value from `rg` command on Windows 10

**Comment by nobiot** [comment] 2020-05-24 14:44
Back to the original issue of sqlite3, I'm very happy to learn that sqlite3 could be made to work.
@notuntoward, @progfolio, I wrote the Windows installation section based on feedback of a couple of people and my own experience. I'll be happy to try to update it with this if you are happy with me doing it -- @notuntoward I'll be more than happy if you can give a go at it, too.

**Comment by nobiot** [comment] 2020-05-24 17:04
For the original issue, I have created a PR #696 for review. Thank you.

**Comment by jethrokuan** [comment] 2020-05-25 05:14
> Setting it back to the old way (setq org-roam-list-files-commands '(elisp)) got me going for now.

Yeah it looks like the find and rg methods don't really work with windows. I'll set the default value for windows to nil.

**Comment by jethrokuan** [comment] 2020-05-25 05:27
#698 addresses the find-file issue.

**Comment by notuntoward** [comment] 2020-05-25 19:39
> 
> 
> I have been wrestling with the `org-roam-find-file-command` issues on my Windows 10 all day today.
> Setting it back to the old way `(setq org-roam-list-files-commands '(elisp))` got me going for now.
> 
> My gentle suggestion is to make `elisp` its default value.

Hi @nobiot, thanks for the contributions.  

I like your suggestion to make `elisp` the default value for Windows users.  I'm sure that will save a lot of headaches for the maintainers.

But for me on Windows, `rg` works fine, and should be faster than `elisp`.  I tried `rg` both with an existing roam directory, and with one I created from scratch (delete all roam directories, and then `M-x org-roam-find-file`).  It works for me because it's basically linux, compiled on Windows -- mine distributed by  `choco`.  

Windows `find`, however is definitely not compatible with unix `find`.

**Comment by notuntoward** [comment] 2020-05-25 19:41
> 
> 
> > Setting it back to the old way (setq org-roam-list-files-commands '(elisp)) got me going for now.
> 
> Yeah it looks like the find and rg methods don't really work with windows. I'll set the default value for windows to nil.

@jethrokuan, for me `rg` works fine on Windows but `find` doesn't.

**Comment by nobiot** [comment] 2020-05-26 05:18
> 
> 
> > > Setting it back to the old way (setq org-roam-list-files-commands '(elisp)) got me going for now.
> > 
> > 
> > Yeah it looks like the find and rg methods don't really work with windows. I'll set the default value for windows to nil.
> 
> @jethrokuan, `rg` works fine for me on Windows but `find` doesn't. This is on `org-roam` version 1.1.1 from melpa.

@notuntoward, Thank you. I would love to use `rg` for performance. For me, `rg` seemed to have worked on the surface: It works on `PowreShell` and `cmd`, but within `org-roam`, there was a weird behaviour.

There was no apparent error with `rg` with `org-roam` on my Windows 10, either. What I have observed is the titles of notes did not get correctly reflected in `org-roam-buffer` right after launch of org-roam (after building db-cache). `org-roam-buffer` showed file names instead, when titles exists (and `elisp` search shows them). The weird thing is `org-roam-insert` seemed to correctly show the titles even with `rg`. In the end, I started getting an error message that says something about "UNIQUE" -- sorry, I did not record this error message, but this error made`org-roam` stop working completely for me (everything works now with the default `elisp` find method).

I stopped analysing this problem as`elisp` worked, and reported the weird `\\` issue I reported initially (assuming it had something to do with the title and "UNIQUE" problem.

Do you not have the same `\\` issue, and do not have the issue with the title in `org-roam-buffer`?
If so... I would love to dig further to see if the problem is related to my set up and PC.

**Comment by notuntoward** [comment] 2020-05-26 14:41
@nobiot, @jethrokuan after making more `org-roam` notes than I had initially, and then retesting, I now also have problems with `rg`

When I have `(org-roam-list-files-commands '(rg))`, I don't see the exact errors seen by @nobiot, but I'm not able to build and display a graph; when I run `org-roam-graph`, I see a box for every note but there are no edges connecting them. 

With `(org-roam-list-files-commands nil)`  I see a graph with edges as expected.

So, I'll also go back to the default `elisp`.

**Comment by nobiot** [comment] 2020-05-27 16:46
I use `rg-mode` with no problem (as far as I can see) on my Windows 10, so I don't think the `rg`  option has hit the dead end yet.  It's not critical and priority for me with the size of my notes (counting 113). Something we might want to come back to at a later stage 👍

**Comment by jethrokuan** [comment] 2020-05-28 13:21
Closing this issue, tracking the `rg` issues in #724.

**Closed by jethrokuan** 2020-05-28 13:21 UTC
Labels: enhancement
