### ISSUE TITLE
auto-save asks for file name for *org-roam* buffer

### ISSUE THREAD

**Issue by zoechi** [org-roam/org-roam#566] opened 2020-05-04 15:32 UTC
### Description
I have auto-save enabled and as soon as I write a character in `*org-roam*` buffer auto-save keeps asking for a file name opening a GUI file dialog.

I'm still a novice with Emacs. 
As far as I understand this means that `*org-roam*` somehow looks like a buffer that is associated with a file.

Is this necessary or is this by mistake?

I could skip the `*org-roam*` buffer from the auto-save function, but I didn't have such an issue with any other package.

#### Steps to Reproduce

I use this setup for auto-save
```
(auto-save-visited-mode 1)

(defun full-auto-save ()
  "Save all buffers on auto-save."
  (interactive)
  (save-excursion (dolist (buf (buffer-list))
                    (set-buffer buf)
                    (if (and (buffer-file-name)
                             (buffer-modified-p))
                        (basic-save-buffer)))))
(add-hook 'auto-save-hook #'full-auto-save)

(defun save-all ()
  "Save all buffers on focus out."
  (interactive)
  (save-some-buffers t))

;; do not ask for confirmation before saving
;; from https://emacs.stackexchange.com/a/51829/26301
(defun set-buffer-save-without-query ()
  "Set `buffer-save-without-query' to t."
  (unless (variable-binding-locus 'buffer-save-without-query)
    (setq buffer-save-without-query t)))

(add-hook 'find-file-hook #'set-buffer-save-without-query)

;; The following avoids being ask to allow the file local
;; setting of `buffer-save-without-query'.
;; IMHO it is not a big risk:
;; The malicious code that must not be saved
;; should never be allowed to enter Emacs in the first place.
(put 'buffer-save-without-query 'safe-local-variable 'booleanp)

(advice-add (symbol-function 'after-focus-change-function)
            :after 'save-all)
```
`M-x` `org-roam` to open the `*org-roam*` buffer.
Write a character in that buffer and wait a few seconds.

The file dialog appears.

### Versions
- Emacs (`C-h v emacs-version`): v28.0.50
- Org-roam: 20200504.1547

**Comment by zaeph** [comment] 2020-05-04 15:34
> I have auto-save enabled and as soon as I write a character in `*org-roam*` buffer auto-save keeps asking for a file name opening a GUI file dialog.

Can you tell us why you would want to write in the `org-roam-buffer`?  It's supposed to be redone every time you visit an Org-roam file.

**Comment by zoechi** [comment] 2020-05-04 15:37
Actually I just installed org-roam and try to figure out how to use it and have no clue yet what that buffer is supposed to do. I just found out it exists.
I accidentally pressed a key while the buffer had the focus and the dialog started popping up.
If there is no point in writing perhaps the buffer should be read-only?

**Comment by zaeph** [comment] 2020-05-04 15:38
> I accidentally pressed a key while the buffer had the focus and the dialog started popping up.
> If there is no point in writing perhaps the buffer should be read-only?

It is read-only by default, which is why it is weird that you could even write in it in the first place.  Did you encounter an error when loading `org-roam-mode`, or whilst opening the `org-roam-buffer` with `M-x org-roam`?

**Comment by zoechi** [comment] 2020-05-04 16:09
I think the problem is caused by calling `M-x` `org-roam` while the current buffer is not an Org file.
It doesn't show an error, but something doesn't seem right.


Another question - I hope you don't mind:
Is there a good way to have the org-roam buffer automatically opened when an org-file is opened?
```
(use-package org-roam
  :ensure t
  :hook
  (after-init . org-roam-mode)
  (org-mode . org-roam)
  ...
```
causes
```
Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  #<subr select-window>(nil)
  apply(#<subr select-window> nil)
  select-window(nil)
  org-roam-buffer--get-create()
  org-roam()
```

**Comment by zaeph** [comment] 2020-05-04 16:11
> I think the problem is caused by calling `M-x` `org-roam` while the current buffer is not an Org file.
> It doesn't show an error, but something doesn't seem right.

I cannot reproduce this on my end: running `M-x org-roam` in a non-org, non-Org-roam buffer display the `org-roam-buffer` without any error, and it is read-only.

Can you make sure you're using the latest version of Org-roam available from MELPA?

> Is there a good way to have the org-roam buffer automatically opened when an org-file is opened?

Do you mean any Org-mode file, or just the Org-roam files?

**Comment by zoechi** [comment] 2020-05-04 16:14
The `org-roam` buffer doesn't seem to recover from that.
When I add the org-roam buffer from a buffer that is not a org-mode buffer, close it and open it while an org-mode buffer has the focus, it still only opens the broken org-roam buffer. I had to restart Emacs to make it work again (show the headlines).

**Comment by zaeph** [comment] 2020-05-04 16:18
> The `org-roam` buffer doesn't seem to recover from that.
> When I add the org-roam buffer from a buffer that is not a org-mode buffer, close it and open it while an org-mode buffer has the focus, it still only opens the broken org-roam buffer. I had to restart Emacs to make it work again (show the headlines).

OK, now I can reproduce it.  When the `org-roam-buffer` is killed and reopened from a non-Org-roam file, it will spawn empty, and in `fundamental-mode`.  Moving to another Org-roam file does not repair the `org-roam-buffer`, since the mode is not active.

We haven't encountered this behaviour yet because you're not supposed to _kill_ the `org-roam-buffer`, but merely bury it by running `M-x org-roam` again (or whatever key-binding you've set it to).

**Comment by zoechi** [comment] 2020-05-04 16:21
> Can you make sure you're using the latest version of Org-roam available from MELPA?

I just installed it using `(use-package org-roam :ensure t ...)`, so I'd assume it is the latest. The version is `Org-roam: 20200504.1547`

> Do you mean any Org-mode file, or just the Org-roam files?

I'm not sure yet what the difference is. When is an org-mode buffer not an org-roam buffer? When it is not from inside the org-roam-directory?
Actually both would be fine (just org-roam, or org-roam **AND** org-mode)
I guess there will only be few org files outside that directory, but as mentioned, I just started and might have limited ideas how this will turn out.

**Comment by zaeph** [comment] 2020-05-04 16:22
> I'm not sure yet what the difference is. When is an org-mode buffer not an org-roam buffer? When it is not from inside the org-roam-directory?

Yes: an Org-roam file is a file that lives inside your `org-roam-directory`.

**Comment by zoechi** [comment] 2020-05-04 16:27
From your responses I get the impression that having that buffer visible most of the time in org-(roam) files is not that common. Perhaps I need to dive into it more before asking questions. 

Thanks for your super-fast response. Incredible :+1:

**Comment by zaeph** [comment] 2020-05-04 16:31
> From your responses I get the impression that having that buffer visible most of the time in org-(roam) files is not that common. Perhaps I need to dive into it more before asking questions.

I think someone mentioned the other day that Doom Emacs had gone that way, and made the `org-roam-buffer` pop up whenever visiting an Org-roam file.  You might want to investigate on that front.

> Thanks for your super-fast response. Incredible +1

Eh, I was just around. :)

**Comment by zoechi** [comment] 2020-05-04 16:41
> Doom Emacs had gone that way

In case anybody stumbles upon this discussion: 
I found https://github.com/hlissner/doom-emacs/blob/e832ec570894699a4e94a7697e38c100d2594c38/modules/lang/org/contrib/roam.el#L53 where they use `find-file-hook`

**Closed** 2021-07-17 15:27 UTC
Labels: bug
