### ISSUE TITLE
Node removed from database just after alias added

### ISSUE THREAD

**Issue by grafov** [org-roam/org-roam#1976] opened 2021-11-19 23:49 UTC
### Description

Node removed from the database just after alias added.

#### Steps to Reproduce

1. Load Emacs
2. Create a new node with `org-roam-node-find`, for example I set title "test"
3. Press `C-c` to complete the node.
4. Node successfully searched with `org-roam-node-find` by its title "test node".
5. Add alias for the node with `org-roam-alias-add`, for example I add "test node 2"
6. Save the buffer.
7. Try to find it again by its title or alias -- no success.

After that I see that this node was removed from `nodes` and `aliases` tables. But still remains in `files`. 
The buffer and file still exist too. Buffer looks like this (I slighltly modified the default template for adding date and tags):

```
:PROPERTIES:
:ID:       a8a20b61-8f09-4913-9e90-740696ae1dad
:ROAM_ALIASES: "test node 2"
:END:
#+title: test node
#+created: [2021-11-20 Сб]
#+filetags:
```

Run `org-roam-db-sync` didn't help.

#### Messages buffer 

I tried to run `org-roam-db-diagnose-node` after each step and got:

```
#s(org-roam-node nil nil nil nil nil "a8a20b61-8f09-4913-9e90-740696ae1dad" nil 1 nil nil nil nil nil nil nil nil nil nil)
Wrote /home/a/org/roam/20211120023511-test_node.org
#s(org-roam-node "/home/a/org/roam/20211120023511-test_node.org" "test node" nil (24984 13503 260016 487000) (24984 13503 251016 281000) "a8a20b61-8f09-4913-9e90-740696ae1dad" 0 1 nil nil nil nil "test node" (("CATEGORY" . "20211120023511-test_node") ("ID" . "a8a20b61-8f09-4913-9e90-740696ae1dad") ("BLOCKED" . "") ("FILE" . "/home/a/org/roam/20211120023511-test_node.org") ("PRIORITY" . "B")) nil nil nil nil)
Quit [2 times]
#s(org-roam-node "/home/a/org/roam/20211120023511-test_node.org" "test node" nil (24984 13503 260016 487000) (24984 13503 251016 281000) "a8a20b61-8f09-4913-9e90-740696ae1dad" 0 1 nil nil nil nil "test node" (("CATEGORY" . "20211120023511-test_node") ("ID" . "a8a20b61-8f09-4913-9e90-740696ae1dad") ("BLOCKED" . "") ("FILE" . "/home/a/org/roam/20211120023511-test_node.org") ("PRIORITY" . "B")) nil nil nil nil)
Saving file /home/a/org/roam/20211120023511-test_node.org...
Wrote /home/a/org/roam/20211120023511-test_node.org
Quit
nil
```

As  you see in the end (after Quit) I see `nil` as result of `org-roam-db-diagnose-node`. 

#### Expected Results

After adding the alias node still exists in the database. It could be searched with original title and with alias.

#### Actual Results

No more node in the database.

### Environment
```
`M-x org-roam-diagnostics`
- Emacs: GNU Emacs 27.2 (build 1, x86_64-unknown-linux-gnu, GTK+ Version 3.24.26)
 of 2021-03-26
- Framework: N/A
- Org: Org mode version 9.5 (9.5-g494c20 @ /home/a/.emacs.d/straight/build/org/)
- Org-roam: v2.1.0-62-g1af1639
```

##### Workaround

I tried different variants of titles and aliases, i.e. words without spaces, words in Cyrillic and so on -- bug still appeared in any conditions. All the nodes and aliases restored if I rebuild database:
1. Exit GNU/Emacs
2. Remove org-roam.db file
3. Run GNU/Emacs
4. All the nodes and aliases available again.

**Comment by jethrokuan** [comment] 2021-11-23 13:42
Everything seems to be working fine on my end:

```
#s(org-roam-node "/home/jethro/Dropbox/org/braindump/org/test_node.org" "test node" nil (24988 61267 10441 423000) (24988 61267 10441 423000) "a8a20b61-8f09-4913-9e90-740696ae1dad" 0 1 nil nil nil nil "test node" (("CATEGORY" . "test_node") ("ROAM_ALIASES" . "\"test node 2\"") ("ID" . "a8a20b61-8f09-4913-9e90-740696ae1dad") ("BLOCKED" . "") ("FILE" . "/home/jethro/Dropbox/org/braindump/org/test_node.org") ("PRIORITY" . "B")) nil nil ("test node 2") nil) [2 times]
```

```
- Emacs: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-11-21
- Framework: Doom
- Org: Org mode version 9.5 (9.5-??-cc2490a70 @ /home/jethro/.emacs.d/.local/straight/build-29.0.50/org/)
- Org-roam: v2.1.0-67-gae533fa
```

**Comment by prashantnag93** [comment] 2021-12-06 10:05
@jethrokuan I am also facing the same problem.

**Comment by tarlaw** [comment] 2021-12-09 02:26
same problem.
```
- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-27
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-27edae8ce @ /home/law/.emacs.d/.local/straight/build-27.2/org/)
- Org-roam: abe63b4
 ```

**Comment by ntharim** [comment] 2021-12-09 09:48
The root cause is https://github.com/yantar92/org/issues/40. As the fix has been merged recently https://github.com/emacs-straight/org-mode/commit/54534eebbb75ea4690225ecb80ac20f9b7bd1713, try updating Org.

**Comment by grafov** [comment] 2022-01-07 01:09
> What db connector are you using? Is it the default?

@jethrokuan I have default value `sqlite` for `org-roam-database-connector`.

@ntharim the bug disappeared for me after updating to org 9.5.2 so you have pointed the right cause! I can't reproduce it anymore.

Thank you all for help!

**Comment by rodelrod** [comment] 2022-01-09 23:20
Had the same problem here. A `doom upgrade` + `doom build` pulled the latest version of Org and fixed it.

**Closed** 2022-01-16 04:32 UTC
Labels: 1. bug, 1. upstream
