### ISSUE TITLE
Emacs only since this week won't even start, hangs indefinitely on Windows10

### ISSUE THREAD

**Issue by herop** [org-roam/org-roam#1067] opened 2020-08-25 09:57 UTC
**Describe the bug**

- Since Monday (Sunday still was all good) 
- Hard to describe since Emacs won't even fully start and debug info is not showing.
- I have the most recent versions of org-roam on Windows10 with Emacs 27.0.91
- I downloaded the sqlite3 V. 3.33.0 and is recognized by and active

Thats my Messages Buffer:
Building straight...done
Building org-plus-contrib...done
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el (source)...
Unicode Fonts - Mapping Unicode Blocks in fontset-default ... done
Unicode Fonts - Mapping Overrides in fontset-default ... done
Unicode Fonts - Mapping Unicode Blocks in fontset-startup ... done
Unicode Fonts - Mapping Overrides in fontset-startup ... done
Unicode Fonts - Mapping Unicode Blocks in fontset-standard ... done
Unicode Fonts - Mapping Overrides in fontset-standard ... done
[yas] Prepared just-in-time loading of snippets successfully.
Building company-org-roam...
Building company-org-roam → Building company...done
Building company-org-roam → Building dash...done
Building company-org-roam → Building org-roam...
Building company-org-roam → Building org-roam → Building f...
Building company-org-roam → Building org-roam → Building f → Building s...done
Building company-org-roam → Building org-roam → Building f...done
Building company-org-roam → Building org-roam → Building org...done
Building company-org-roam → Building org-roam → Building emacsql...done
Building company-org-roam → Building org-roam → Building emacsql-sqlite...done
Building company-org-roam → Building org-roam...done
Building company-org-roam...done
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el (source)...done
Loaded c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el
Cleaning up the recentf list...done (0 removed)
custom-initialize-reset: EmacSQL had an unhandled condition: "near line 13: database is locked" _Ignore, since I have to start a Emacs twice (with one instance still running to see anything but an empty Emacs-Window._
Package cl is deprecated
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el (source)...
[yas] Prepared just-in-time loading of snippets successfully.
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el (source)...done
Loaded c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el

**To Reproduce**
1. Start Emacs
2. Wait indefinitely
3. Start Emacs again
4. Have 2 Windows of Emacs with the one "Working" incapable to use sqlite3 meaning org-roam is not at all usable 

**Expected behavior**
As before this week, just start and let me use Emacs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
![sqlite3-Version](https://user-images.githubusercontent.com/658323/91160623-ed2a2a80-e6c9-11ea-8bbf-48691d9716c1.png)
![Emacs-Window](https://user-images.githubusercontent.com/658323/91160737-12b73400-e6ca-11ea-9c3c-2e19085f4dba.png)

**Comment by ahristow** [comment] 2020-08-25 15:28
Prior to having this problem were you using an earlier version of org-roam? This looks like it could be a duplicate of #1038 .

**Comment by herop** [comment] 2020-08-25 19:51
I update daily (like just about 1h ago) :-). But I have great news: Emacs is starting again, but still veeery slow:
So, is it necessary at each start to do all this (and if not, any idea what I could do to change it?): - Message buffer -
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el (source)...
Unicode Fonts - Mapping Unicode Blocks in fontset-default ... done
Unicode Fonts - Mapping Overrides in fontset-default ... done
Unicode Fonts - Mapping Unicode Blocks in fontset-startup ... done
Unicode Fonts - Mapping Overrides in fontset-startup ... done
Unicode Fonts - Mapping Unicode Blocks in fontset-standard ... done
Unicode Fonts - Mapping Overrides in fontset-standard ... done
[yas] Prepared just-in-time loading of snippets successfully.
Building company-org-roam...
Building company-org-roam → Building company...done
Building company-org-roam → Building dash...done
Building company-org-roam → Building org-roam...
Building company-org-roam → Building org-roam → Building f...
Building company-org-roam → Building org-roam → Building f → Building s...done
Building company-org-roam → Building org-roam → Building f...done
Building company-org-roam → Building org-roam → Building org...done
Building company-org-roam → Building org-roam → Building emacsql...done
Building company-org-roam → Building org-roam → Building emacsql-sqlite...done
Building company-org-roam → Building org-roam...done
Building company-org-roam...done
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el (source)...done
Loaded c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el
(org-roam) files: Δ0, headlines: Δ0, links: Δ0, tags: Δ0, titles: Δ0, refs: Δ0, deleted: Δ0
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
For information about GNU Emacs and the GNU system, type C-h C-a.
Package cl is deprecated
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el (source)...
[yas] Prepared just-in-time loading of snippets successfully.
Loading c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el (source)...done
Loaded c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/.emacs.d/config.el

**Comment by aaronbieber** [comment] 2020-09-05 10:15
@herop Please use a source code formatting block when pasting in raw text. Select the entire block of pasted text and click the toolbar button that looks like `<>`.

**Comment by nobiot** [comment] 2020-09-17 09:51
New PR #1103 has been merged with the master branch.
It would great if someone could test if it solves this issue. Thanks.

**Comment by jethrokuan** [comment] 2020-09-30 05:35
Closing this since `file-truename` calls are now mostly gone, and the original issue shouldn't exist anymore.

**Closed by jethrokuan** 2020-09-30 05:35 UTC
Labels: waiting-for-reply, windows
