### ISSUE TITLE
Performance issues on large files

### ISSUE THREAD

**Issue by brettmilford** [org-roam/org-roam#940] opened 2020-07-15 10:39 UTC
### Description
Emacs hangs for a considerable time (~20 seconds) when saving a particular org-mode file and org-roam mode is enabled.
The file is ~1300 lines long, it was previously ~6k but I reduced it to see if it would improve the issue (it did, but only slightly)
Is there an expected file size, or known upper limit on what can be processed is a reasonable amount of time? Running profile seems to suggest its spending most of its time parsing the file.

#### Steps to Reproduce

1. Load an org file of >1300 lines with org-roam on
2. Edit and save the file

#### Expected Results

Emacs completes the save and returns input.

#### Actual Results

Emacs hangs for a considerable amount of time before returning.

#### Profile

```
- command-execute                                                1524  92%
 - call-interactively                                            1524  92%
  - funcall-interactively                                        1524  92%
   - evil-ex                                                     1422  86%
    - apply                                                      1422  86%
     - +ivy--inhibit-completion-in-region-a                      1422  86%
      - let                                                      1422  86%
       - apply                                                   1422  86%
        - #<compiled 0x41279e11>                                 1422  86%
         - evil-ex-execute                                       1413  85%
          - eval                                                 1413  85%
           - evil-ex-call-command                                1413  85%
            - call-interactively                                 1413  85%
             - funcall-interactively                             1412  85%
              - evil-write                                       1412  85%
               - save-buffer                                     1412  85%
                - basic-save-buffer                              1412  85%
                 - run-hooks                                     1408  85%
                  - org-roam-db--update-file                     1374  83%
                   - org-roam-db--update-links                   1214  73%
                    - org-roam--extract-links                    1211  73%
                     - org-element-map                           1187  71%
                      + #<compiled 0x437e6ef9>                   1187  71%
                     + org-element-parse-buffer                    23   1%
                     + file-truename                                1   0%
                    + org-roam-db-query                             2   0%
                    + file-truename                                 1   0%
                   + org-roam-db--update-titles                    47   2%
                   + org-roam-db--update-tags                      36   2%
                   + org-roam-db--update-headlines                 30   1%
                   + org-roam-db--update-refs                      25   1%
                   + org-roam-buffer--update-maybe                 14   0%
                   + org-roam-db--update-meta                       6   0%
                   + org-roam--org-roam-file-p                      2   0%
                  + undo-fu-session-save-safe                      30   1%
                  + org-encrypt-entries                             1   0%
                  + doom-modeline-update-buffer-file-name                  1   0%
                  + +evil-display-vimlike-save-message-h                  1   0%
                  + doom-auto-revert-buffers-h                      1   0%
                 + basic-save-buffer-1                              2   0%
                   vc-before-save                                   1   0%
                 + run-hook-with-args-until-success                  1   0%
             + byte-code                                            1   0%
         + read-from-minibuffer                                     7   0%
   + undo-fu-only-undo                                             51   3%
   + counsel-load-theme                                            33   2%
   + org-cycle                                                      7   0%
   + undo-fu-only-redo                                              4   0%
   + doom/toggle-profiler                                           3   0%
   + org-metaup                                                     2   0%
   + evil-previous-line                                             1   0%
   + doom/escape                                                    1   0%
+ ...                                                             101   6%
+ timer-event-handler                                              14   0%
+ redisplay_internal (C function)                                  10   0%
```

### Environment

- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/brett/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.0

**Comment by ddxgz** [comment] 2020-07-20 18:24
Seems a Duplicate of #834

**Comment by jethrokuan** [comment] 2021-07-17 15:41
Org-roam v2 should be much faster now, feel free to reopen if things still feel too slow.

**Closed by jethrokuan** 2021-07-17 15:41 UTC
